# -*- coding: utf-8 -*-
"""ES translations batch 3/5: flan, habichuelas, majarete, mallorcas, papa-rellena."""

DATA = {
    "flan": {},  # handled from direct page read below
    "habichuelas": {
        "title": "Habichuelas Guisadas — Receta Puertorriqueña de Habichuelas Guisadas",
        "desc": "Aprende a hacer habichuelas guisadas, las clásicas habichuelas puertorriqueñas con calabaza, sofrito y sazón. Un guiso espeso y savory que va con todo.",
        "eyebrow": "Acompañantes y Arroz",
        "trust": ["35 minutos", "Fácil"],
        "serves": "Para 6 porciones:",
        "intro": "Si hay un acompañante que pertenece a todo plato puertorriqueño, son las <b>habichuelas guisadas</b> — habichuelas guisadas espesas y savories que cocinan a fuego lento hasta que el caldo se vuelve aterciopelado y la calabaza se derrite en la salsa. Mientras el arroz con gandules acapara los titulares, las habichuelas guisadas son el caballo de batalla silencioso de la cocina, el plato que hace que un plato simple de arroz blanco se sienta como una comida completa. Todo boricua creció con una olla de estas habichuelas hirviendo en la estufa, el olor a sofrito y tomate llenando la casa. El arma secreta es la <i>calabaza</i> — calabaza caribeña que espesa naturalmente el guiso al ablandarse y deshacerse parcialmente. Ya sea junto a arroz y pernil o vertida sobre pasta (sí, eso existe), las habichuelas guisadas son consuelo en un bol.",
        "whatis": [
            "Habichuelas guisadas se traduce simplemente como 'stewed beans' — pero eso le queda corto a lo que pasa en la olla. Las habichuelas rosadas (o a veces rojas) se cocinan a fuego lento en una base de sofrito, pasta de tomate y sazón, con trozos de calabaza que se disuelven en el caldo para crear una consistencia espesa, casi cremosa, sin ninguna crema. A diferencia de los frijoles refritos o los frijoles negros cubanos, las habichuelas guisadas puertorriqueñas son chunky y jugosas — lo bastante espesas para cubrir una cuchara pero lo bastante sueltas para verterse sobre el arroz. La calabaza es el ingrediente clave que distingue esto de cualquier otro guiso de habichuelas del Caribe. Al cocinarse, se ablanda y se deshace parcialmente, espesando naturalmente el caldo y añadiendo un dulzor sutil que balancea la base savory de tomate y sofrito.",
            "Encontrarás habichuelas guisadas en prácticamente cada comida puertorriqueña — desde almuerzos de semana hasta banquetes navideños. Es el acompañante que nunca se salta, el plato en el que los niños mojan sus tostones, y las sobras que saben aún mejor al día siguiente revueltas en un bol de arroz. Algunas familias las hacen con habichuelas rojas, otras con rosadas, y otras con gandules, pero el método siempre es el mismo: sofrito, tomate, calabaza, paciencia.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="2" data-unit="cans">2 latas</span> (15 oz) de habichuelas rosadas</b> — NO escurras. El líquido es lo que construye el cuerpo del guiso. Las Goya rosadas son el estándar.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4 taza</span> de sofrito</b> — casero o comprado. La columna aromática de todo el plato.',
            '<b><span class="ing-qty" data-base="2" data-unit="tablespoons">2 cucharadas</span> de pasta de tomate</b> — añade profundidad y color. Cocínala brevemente para caramelizarla y quitarle el sabor crudo.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2 taza</span> de calabaza en cubos</b> — calabaza caribeña, en pedazos de 1 pulgada. Encuéntrala congelada en supermercados latinos o sustituye con butternut.',
            '<b><span class="ing-qty" data-base="1" data-unit="packet">1 sobrecito</span> de sazón con culantro y achiote</b> — para color y ese sabor puertorriqueño característico.',
            '<b><span class="ing-qty" data-base="1" data-unit="teaspoon">1 cucharadita</span> de comino</b> — cálido y terroso, combina perfecto con las habichuelas.',
            '<b><span class="ing-qty" data-base="1" data-unit="cup">1 taza</span> de agua</b> — para afinar el guiso a la consistencia correcta. Usa caldo de pollo para extra riqueza.',
            '<b><span class="ing-qty" data-base="2" data-unit="tablespoons">2 cucharadas</span> de aceite</b> — vegetal u oliva para sofreír el sofrito.',
            '<b>Sal al gusto</b>',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay calabaza?</b> La butternut es el sustituto más cercano — mismo dulzor y textura blanda al cocinarse. La calabaza de azúcar también funciona.",
            "<b>¿No hay habichuelas rosadas?</b> Las rojas kidney son la alternativa más común. Las pintas funcionan en apuros, aunque el sabor es más suave.",
            "<b>¿No hay sofrito?</b> Pica 3 dientes de ajo + 1/4 taza de cebolla + 1/4 taza de pimiento verde + unos tallos de cilantro. No será igual, pero te acerca.",
        ],
        "steps": [
            "<b>Sofríe el sofrito.</b> Calienta aceite en una olla mediana a fuego medio. Añade el sofrito y cocina 3 minutos, revolviendo seguido, hasta que ablande y llene la cocina con ese aroma inconfundible.",
            "<b>Añade la pasta de tomate.</b> Incorpora la pasta de tomate y cocina 1 minuto, dejándola caramelizar ligeramente. Este paso profundiza el sabor y elimina cualquier gusto a lata.",
            "<b>Añade calabaza y especias.</b> Echa los cubos de calabaza, el sobrecito de sazón y el comino. Revuelve hasta que la calabaza esté cubierta por la base de sabor. El achiote del sazón empezará a pintar todo de ese hermoso naranja-rojo.",
            "<b>Añade habichuelas y agua.</b> Vierte ambas latas de habichuelas — líquido incluido — más la taza de agua. Revuelve todo y lleva a hervir.",
            "<b>Cocina a fuego lento 20 minutos.</b> Baja el fuego a medio-bajo y deja burbujear suavemente. La calabaza ablandará, el caldo espesará, y los sabores se integrarán. Revuelve ocasionalmente para que nada se pegue.",
            "<b>Machaca y sirve.</b> Usa el dorso de la cuchara para machacar algunos trozos de calabaza contra el lado de la olla. Ese es el truco que vuelve el caldo espeso y cremoso. Prueba y ajusta la sal — sirve caliente sobre arroz blanco.",
        ],
        "tips_h2": "Consejos para Habichuelas Guisadas Perfectas",
        "tips": [
            "<b>No escurras las habichuelas.</b> El líquido de la lata es almidonado y sabroso — es lo que da cuerpo al guiso. Escúrrelas y tendrás que añadir más espesante.",
            "<b>Machaca algo de calabaza.</b> Este paso no es negociable. Presiona la mitad de los trozos contra la olla para disolverlos en el caldo. Deja el resto entero para textura.",
            "<b>Fuego bajo y lento gana.</b> Un hervor fuerte rompe las habichuelas y vuelve el guiso granulado. Un hervor suave mantiene las habichuelas enteras mientras la calabaza se derrite.",
            "<b>Espesa al enfriar.</b> Si el guiso parece un poco ligero al retirarlo del fuego, dale 5 minutos. Se afirmará. Añade un chorrito de agua al recalentar las sobras.",
        ],
        "faqs": [
            {"q": "¿Puedo usar otros tipos de habichuelas?", "a": "Claro. Las rojas kidney son la alternativa más popular y hacen un guiso más contundente. Las pintas también funcionan pero producen un sabor más suave. Algunas familias usan gandules para una versión más ligera. El método permanece igual sin importar el tipo — solo conserva el líquido de la lata y ajusta el tiempo de cocción si son más grandes."},
            {"q": "¿Qué es la calabaza y dónde la encuentro?", "a": "La calabaza es un tipo de calabaza caribeña — densa, dulce y de carne anaranjada. Es un básico de la cocina puertorriqueña y puede encontrarse congelada en supermercados latinos. Si no la encuentras, la butternut es el mejor sustituto con dulzor y textura similares. La calabaza de azúcar también funciona bien. Evita el puré de calabaza para pie en lata — eso es completamente otra cosa."},
            {"q": "¿Esta receta es vegana?", "a": "Ya lo es tal como está escrita — sin carne, sin lácteos. Solo habichuelas, vegetales y especias. Lo único que vigilar es el sofrito si compras hecho: algunas marcas añaden caldo de pollo, así que revisa la etiqueta. Si usas sofrito casero o una versión vegetal, el plato completo es 100% vegano y delicioso."},
        ],
    },
    "majarete": {
        "title": "Majarete — Receta Puertorriqueña de Postre de Maíz y Coco",
        "desc": "Aprende a hacer majarete, el postre tibio puertorriqueño de maíz y coco. Simple, reconfortante y espolvoreado con canela.",
        "eyebrow": "Postres",
        "trust": ["30 minutos", "Fácil"],
        "serves": "Rinde 6 porciones:",
        "intro": "El <b>majarete</b> es un postre tibio de maíz y coco — el postre humilde y reconfortante que hacía cada abuela puertorriqueña. Es más simple que el tembleque pero igual de querido. Mientras el tembleque se lleva toda la gloria como el pudín de coco de Puerto Rico, el majarete ha estado sentado tranquilamente en la cocina de abuela por generaciones, hecho con nada más que harina de maíz, leche de coco, azúcar y una nevada de canela. Es el tipo de postre que no necesita impresionar a nadie. Simplemente sabe a hogar. Espeso, cremoso, sutilmente dulce y fragante con coco — el majarete es comida reconfortante en su forma más pura. Lo comes tibio de la olla o frío de la nevera; de cualquier manera, es perfecto.",
        "whatis": [
            "El majarete es un pudín tradicional puertorriqueño hecho de harina de maíz y leche de coco. A diferencia del tembleque, que usa maicena y cuaja firme para desmoldar, el majarete se hace con harina de maíz, lo que le da una textura ligeramente granulada, tipo papilla. Se cocina en la estufa hasta espesar, luego se vierte en tacitas individuales o un plato grande y se refrigera. El resultado es un pudín más denso y texturizado que el tembleque, con un sabor cálido y tostado a maíz que combina bellamente con el coco.",
            "El majarete es un postre de todo el año en Puerto Rico, pero aparece especialmente en reuniones familiares y mesas navideñas. Algunos lo sirven tibio directo de la olla — casi como una papilla — mientras otros lo prefieren frío y firme. De cualquier manera, la tapa espolvoreada de canela no es negociable. Es un postre con raíces en la herencia taína indígena de la isla, donde el maíz era un básico alimentario mucho antes de la llegada de los españoles.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="1" data-unit="cup">1 taza</span> de harina de maíz</b> — molido fino o medio. No polenta gruesa — lo quieres suave.',
            '<b><span class="ing-qty" data-base="2" data-unit="cans">2 latas</span> (13.5 oz cada una) de leche de coco</b> — entera para el sabor más rico. Divide: 1 lata para mezclar y 1 para la olla.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2 taza</span> de azúcar</b> — ajusta al gusto. A algunos les gusta más dulce, otros lo mantienen sutil.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="teaspoon">1/4 cucharadita</span> de canela molida</b> — infusionada en el pudín mismo.',
            '<b>Una pizca de sal</b> — resalta los sabores de coco y maíz.',
            '<b>Canela molida para la cima</b> — el toque final. No lo omitas.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay harina de maíz?</b> Puedes usar maicena, pero la textura será más suave, tipo tembleque. La harina de maíz le da al majarete su carácter ligeramente granulado distintivo.",
            "<b>¿Leche de coco light?</b> Funciona, pero el pudín será menos rico y cremoso. La leche de coco entera vale la pena para esta receta.",
            "<b>¿Lo quieres extra suave?</b> Licúa la mezcla después de integrarla para un resultado más sedoso. El majarete traditional tiene una ligera granulosidad que a la mayoría encanta.",
        ],
        "steps": [
            "<b>Mezcla la harina de maíz.</b> En un bol, bate la harina de maíz con 1 lata de leche de coco hasta completamente suave. Sin grumos — tómate tu tiempo. Esta mezcla es lo que evita grumos al añadirla al líquido caliente.",
            "<b>Calienta la leche de coco.</b> Vierte la lata restante de leche de coco en una olla mediana. Añade azúcar, canela y sal. Calienta a fuego medio hasta que empiece a humear y el azúcar se disuelva.",
            "<b>Combina y cocina.</b> Vierte lentamente la mezcla de harina de maíz en la leche de coco caliente, batiendo constantemente. Sigue batiendo mientras la mezcla comienza a espesar — esto pasa rápido cuando la harina toca el calor.",
            "<b>Cocina 10-15 minutos.</b> Baja el fuego a medio-bajo y revuelve constantemente con cuchara de madera o espátula de silicona. El majarete quedará muy espeso — debe desprenderse de los lados de la olla. No dejes de revolver o se pegará y quemará en el fondo.",
            "<b>Vierte y refrigera.</b> Sirve el majarete caliente en 6 tacitas individuales o un plato solo. Deja enfriar a temperatura ambiente, luego refrigera al menos 2 horas hasta que cuaje.",
            "<b>Esponvorea con canela.</b> Antes de servir, espolvorea las tapas generosamente con canela molida. Sirve frío — o cómetelo tibio directo de la olla. Ambas formas son tradicionales.",
        ],
        "tips_h2": "Consejos para un Majarete Perfecto",
        "tips": [
            "<b>Mezcla la harina de maíz en frío.</b> Siempre mezcla la harina de maíz con líquido frío o a temperatura ambiente primero. Añadir harina seca directamente a líquido caliente crea grumos imposibles.",
            "<b>Revuelve constantemente.</b> La harina de maíz se asienta y se pega rápido. No te alejes de la olla — sigue revolviendo esos 10-15 minutos.",
            "<b>Espesa más al enfriar.</b> El majarete parecerá un poco más ligero de lo que quieres al verterlo. Confía en el proceso — se firma considerablemente en la nevera.",
            "<b>No te saltes la canela.</b> No es solo decoración. La canela encima añade aroma y sabor que completan el postre.",
        ],
        "faqs": [
            {"q": "¿Puedo usar maicena en lugar de harina de maíz?", "a": "Técnicamente sí, pero entonces estarías haciendo esencialmente tembleque — que es otro postre. La maicena produce un pudín suave tipo gel, mientras que la harina de maíz le da al majarete su característica textura ligeramente granulada, tipo papilla. Si quieres majarete, quédate con harina de maíz. Si quieres tembleque, usa maicena y busca esa receta."},
            {"q": "¿Sirvo el majarete tibio o frío?", "a": "Ambos son tradicionales. El majarete tibio es más parecido a una papilla — cremoso, reconfortante, perfecto para mañanas frescas. El majarete frío es más firme y más de postre, con textura más cercana al pudín. La mayoría de las familias lo sirven frío en reuniones, pero comerlo tibio directo de la olla tiene aprobación de abuela."},
            {"q": "¿Puedo añadir pasas al majarete?", "a": "Sí — las pasas son una adición común en algunas familias. Incorpora 1/4 taza de pasas durante los últimos minutos de cocción. Algunas personas también añaden un chorrito de ron o un puñado de coco rallado para textura extra. La versión natural es la clásica, pero las adiciones son comunes y deliciosas."},
        ],
    },
    "mallorcas": {
        "title": "Mallorcas — Receta Puertorriqueña de Pan Dulce",
        "desc": "Aprende a hacer mallorcas, el pan dulce puertorriqueño. Mantecoso, ligeramente denso y perfecto para el desayuno mojado en café con leche. Receta clásica de panadería.",
        "eyebrow": "Panadería",
        "trust": ["2 horas", "Media"],
        "serves": "Rinde 12 panecillos:",
        "intro": "El olor a <b>mallorcas</b> recién salida del horno es el olor a una mañana puertorriqueña. Estos panecillos dulces y mantecosos son parte fija de cada <i>panadería</i> de la isla y un básico de desayuno en hogares boricuas por toda la diáspora. Son un poco más densos que un panecillo de cena, con una miga tierna y un dulzor sutil que los hace perfectos para abrirlos y mojarlos en una taza caliente de café con leche. El nombre viene de la isla española de Mallorca, reflejando las raíces mediterráneas del pan — pero los puertorriqueños lo hicieron completamente suyo. Cada panadería tiene su versión: algunos espiralan la masa, otros los rellenan de guayaba o queso crema, y otros lo mantienen clásico con una montaña de azúcar en polvo encima. Esta receta te da el clásico — un panecillo suave y mantecoso que se prepara con ingredientes simples y un poco de paciencia con la levadura.",
        "whatis": [
            "Las mallorcas son panecillos dulces puertorriqueños — masas enriquecidas hechas con mantequilla, huevos, leche y azúcar, horneadas hasta dorarse y espolvoreadas con azúcar en polvo. Son un tipo de <i>pan dulce</i> que se ha vuelto uno de los artículos más reconocibles de la repostería puertorriqueña. A diferencia de los rollos dulces americanos (tienden a ser ligeros y esponjosos), las mallorcas tienen una textura un poco más densa, más de pan — entre un brioche y un panecillo de cena. No son tan dulces como un rollo de canela, ni tan ricos como un croissant, pero ocupan ese punto medio perfecto que los hace ideales para el desayuno.",
            "Entra a cualquier panadería puertorriqueña temprano en la mañana y las verás apiladas en vitrinas de cristal — espirales doradas espolvoreadas de azúcar blanca en polvo, a veces rellenas de pasta de guayaba o queso crema. Se comen calientes, rotas a mano, mojadas en café, y discutidas (cada familia tiene su panadería preferida). Hacerlas en casa trae esa experiencia de panadería a tu cocina, y aunque el tiempo de levado requiere planear adelante, el trabajo activo es mínimo.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="3" data-unit="cups">3 tazas</span> de harina todo uso</b> — cucharada y nivelada para precisión. La harina de pan también funciona para textura más masticable.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4</span> taza de azúcar</b> — justo para dulzor sutil. No están hechas para saber a postre.',
            '<b><span class="ing-qty" data-base="1" data-unit="packet">1</span> sobre (2 1/4 cdta) de levadura seca activa</b> — revisa la fecha de expiración. Levadura vieja no leva.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2</span> taza de leche tibia</b> — calentada a 110°F (tibia al tacto, no caliente). La leche entera da el resultado más rico.',
            '<b><span class="ing-qty" data-base="0.333" data-unit="cup">1/3</span> taza de mantequilla, ablandada</b> — sin sal, a temperatura ambiente. Esto es lo que hace las mallorcas tiernas y ricas.',
            '<b><span class="ing-qty" data-base="2" data-unit="large">2</span> huevos</b> — a temperatura ambiente para mejor incorporación a la masa.',
            '<b><span class="ing-qty" data-base="1" data-unit="teaspoon">1</span> cucharadita de extracto de vainilla</b> — añade calidez y fragancia sutil al pan.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="teaspoon">1/2</span> cucharadita de sal</b> — balancea el dulzor y fortalece el gluten.',
            '<b>Azúcar en polvo para espolvorear</b> — generosa. Usa un colador fino para un coating parejo.',
        ],
        "swaps_h3": "Variantes",
        "swaps": [
            "<b>Rellenas de guayaba:</b> Aplana cada bola de masa, coloca una cucharada de pasta de guayaba en el centro y dobla cerrando antes de poner boca abajo en la bandeja.",
            "<b>Rellenas de queso crema:</b> Misma técnica — una cucharada de queso crema endulzado en el centro de cada panecillo antes del levado.",
            "<b>Canela y azúcar:</b> Estira la masa plana, unta mantequilla, espolvorea azúcar con canela, enrolla como tronco y corta en 12 espirales. Coloca boca arriba en la bandeja.",
        ],
        "steps": [
            "<b>Activa la levadura.</b> Disuelve la levadura en leche tibia (110°F) con una pizca de azúcar. Déjala reposar 5-10 minutos hasta que haga espuma y burbujee. Si no hace espuma, tu levadura está muerta — empieza de nuevo con levadura fresca.",
            "<b>Mezcla la masa.</b> En un bol grande, bate la harina, el azúcar y la sal. Vierte la mezcla de levadura, añade la mantequilla ablandada, los huevos y la vainilla. Mezcla hasta formar una masa áspera — se verá messy. Eso es normal.",
            "<b>Amasa 10 minutos.</b> Voltea la masa a una superficie enharinada y amasa hasta que esté suave y elástica. Debe regresar lentamente al pincharla. La mantequilla la hará resbalosa al principio — sigue. Se integra.",
            "<b>Primer levado.</b> Coloca la masa en un bol engrasado, cubre con paño húmedo o plástico, y déjala levar en un lugar cálido 1 hora — hasta duplicar. Un horno apagado con la luz encendida es una gran cámara de fermentación.",
            "<b>Forma y segundo levado.</b> Desinfla la masa suavemente y divide en 12 piezas iguales. Enrolla cada una en bola suave y coloca en bandeja 9x13 engrasada (3 filas de 4). Cubre y deja levar otros 30 minutos hasta inflarse.",
            "<b>Hornea y espolvorea.</b> Hornea a 375°F por 18-20 minutos hasta dorar arriba. Mientras aún estén calientes, espolvorea generosamente con azúcar en polvo a través de un colador fino. Sirve calientes con café con leche para la experiencia completa.",
        ],
        "tips_h2": "Consejos para Mallorcas Perfectas",
        "tips": [
            "<b>Chequea tu levadura.</b> Si la mezcla de leche y levadura no hace espuma tras 10 minutos, la levadura está muerta. Empieza de nuevo con levadura fresca y asegúrate de que la leche esté tibia (no caliente) — cualquier cosa sobre 120°F mata la levadura.",
            "<b>No te apures en el levado.</b> El tiempo de levado desarrolla el sabor y la textura. Un levado frío durante la noche en la nevera (bien cubierto) de hecho mejora el sabor — solo trae a temperatura ambiente antes de dar forma.",
            "<b>Ingredientes a temperatura ambiente.</b> La mantequilla y los huevos fríos no se incorporan bien a la masa. Sácalos 30-60 minutos antes de empezar.",
            "<b>Espolvorea mientras calientes.</b> El azúcar en polvo se adhiere mejor cuando los panecillos aún están calientes del horno. Si se enfrían completely, el azúcar se resbala. Sirve dentro de los 30 minutos tras hornear para la mejor experiencia.",
        ],
        "faqs": [
            {"q": "¿Por qué se llaman mallorcas?", "a": "El nombre viene de la isla española de Mallorca en el Mediterráneo. Los colonizadores españoles trajeron las tradiciones panaderas a Puerto Rico, y el pan dulce se asoció con el estilo de horneado de la isla de Mallorca. Con el tiempo, los puertorriqueños adaptaron la receta y la hicieron propia, pero el nombre quedó. En España, un pan similar se llama 'ensaimada' — y puedes rastrear el parecido familiar."},
            {"q": "¿Puedo usar máquina de pan o batidora de pie?", "a": "Sí a ambos. Una batidora de pie con gancho de masa facilita mucho el amasado — usa velocidad media-baja por 6-8 minutos. Para máquina de pan, añade los ingredientes en el orden que recomiende tu máquina (usualmente líquidos primero, luego secos, luego levadura) y usa el ajuste de masa. Cuando termine, da forma a los panecillos y déjalos levar en la bandeja antes de hornear en el horno. La máquina maneja el amasado y primer levado por ti."},
            {"q": "¿Cómo guardo las mallorcas sobrantes?", "a": "Guarda en recipiente hermético a temperatura ambiente por 2-3 días. Están mejores frescas pero siguen buenas un par de días. Para refrescarlas, envuélvelas en papel aluminio y caliéntalas en horno a 300°F por 5-7 minutos. También puedes congelar mallorcas horneadas hasta un mes — descongela a temperatura ambiente y refresca en el horno. Para mejores resultados, congélalas sin azúcar en polvo y espolvorea tras recalentar."},
        ],
    },
    "papa-rellena": {
        "title": "Papa Rellena — Receta Puertorriqueña de Papas Rellenas",
        "desc": "Aprende a hacer papa rellena, papas puertorriqueñas rellenas de carne sazonada. Crujientes, doradas y valen cada calorie.",
        "eyebrow": "Frituras",
        "trust": ["1 hora", "Media"],
        "serves": "Rinde 8 unidades:",
        "intro": "La <b>papa rellena</b> son bolitas de papa rellenas — la comida frita reconfortante que vale cada calorie. Puré de papa suave envolviendo un bolsillo de carne molida sazonada, empanizado y frito hasta que el exterior queda crujiente quebradizo mientras el interior se mantiene cremoso y caliente. Cada cocinero puertorriqueño tiene su versión, y los debates sobre quién hace las mejores son legendarios en las reuniones familiares. Algunos usan más aceitunas, otros añaden pasas, otros insisten en un ratio específico de papa a relleno. Pero la idea central siempre es la misma: toma dos ingredientes humildes — papas y carne molida — y transfórmalos en algo que hace que la gente cierre los ojos y gima con el primer bocado. Esta receta hace 8 papas rellenas generosas, que nunca son suficientes.",
        "whatis": [
            "La papa rellena — literalmente 'papa rellena' — es una de las frituras más icónicas de Puerto Rico. Comienza con papas machacadas suaves y cremosas formadas en bola alrededor de un relleno savory de carne molida llamado picadillo, luego empanizada y frita hasta dorar. El contraste entre el exterior crujiente y el interior suave y vaporoso es lo que hace irresistible este plato. El relleno de carne suele sazonarse con sofrito, sazón, salsa de tomate y aceitunas — la misma base que saboriza tantos platos puertorriqueños.",
            "Encontrarás papa rellena en kioscos, panaderías y reuniones familiares por todo Puerto Rico. Son comida de fiesta popular porque pueden armarse anticipadamente y freírse justo antes de servir. En la diáspora, son el plato que todo boricua hace cuando quiere impresinar invitados o satisfacer un antojo de lo auténtico. Algunas familias las sirven con kétchup, otras con mayonesa de ajo, y los puristas las comen naturales para apreciar el contraste de texturas. Como sea que las sirvas, la papa rellena es prueba de que los ingredientes más simples, tratados con cuidado, pueden producir algo extraordinario.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="2" data-unit="lbs">2 libras</span> de papas, peladas</b> — las almidonadas como Russet funcionan mejor. Se machacan suaves y se mantienen unidas al formar las bolas.',
            '<b><span class="ing-qty" data-base="1" data-unit="lb">1 libra</span> de carne molida</b> — 80/20 regular para sabor. La extra magra hará el relleno seco.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4</span> taza de sofrito</b> — la base aromática del relleno de carne.',
            '<b><span class="ing-qty" data-base="1" data-unit="packet">1</span> sobrecito de sazón</b> — con culantro y achiote para color y profundidad en el relleno.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2</span> taza de salsa de tomate</b> — le da al relleno humedad y riqueza de tomate.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4</span> taza de aceitunas, picadas</b> — manzanilla con pimiento. Los toques salobres en el relleno son esenciales.',
            '<b><span class="ing-qty" data-base="1">1</span> huevo, batido</b> — para el baño de huevo que ayuda a adherir la cobertura de harina.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2</span> taza de harina</b> — todo uso para pasar las bolas antes del baño de huevo.',
            '<b>Aceite para freír</b> — vegetal o canola con alto punto de humo.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay sofrito?</b> Pica 3 dientes de ajo + 1/4 taza de cebolla en cubos + 1/4 taza de pimiento verde en cubos. Sofríe hasta ablandar antes de añadir la carne.",
            "<b>¿No hay sazón?</b> Usa 1 cdta de paprika + 1/2 cdta de ajo en polvo + 1/4 cdta de comino. El color no será tan naranja, pero el sabor funciona.",
            "<b>¿Prefieres hornear en vez de freír?</b> Puedes hornear a 400°F por 25 minutos, pero perderás el exterior crujiente que hace especial la papa rellena.",
        ],
        "steps": [
            "<b>Hierve y machaca las papas.</b> Coloca las papas peladas en una olla grande, cúbrelas con agua con sal y hierve hasta que estén tiernas al tenedor (unos 15 minutos). Escurre completamente y machaca hasta suavidad — sin grumos. Deja enfriar un poco.",
            "<b>Haz el relleno de picadillo.</b> Dora la carne molida en un sartén a fuego medio-alto, desmenuzándola mientras cocina. Añade el sofrito, el sazón, la salsa de tomate y las aceitunas picadas. Cocina 5 minutos hasta que los sabores se integren. Retira del fuego y deja enfriar completely — el relleno tibio derretirá la papa.",
            "<b>Forma las bolas.</b> Toma unas 1/3 taza de puré de papa y aplánala en tu palma. Añade una cucharada generosa del relleno de carne enfriado en el centro. Dobla la papa por encima y sella en una bola suave, del tamaño de una pelota de tenis. Repite con el resto.",
            "<b>Empaniza las bolas.</b> Pasa cada bola por la harina, sacudiendo el exceso. Luego sumérgela en el huevo batido, dejando escurrir el exceso. Esta cobertura en dos pasos crea la costra crujiente al freírse.",
            "<b>Fríe hasta dorar.</b> Calienta aceite a 350°F en un sartén u olla profunda. Baja las bolas de papa al aceite con cuidado y fríe 3-4 minutos, girando ocasionalmente, hasta dorado profundo por todos lados. Escurre en toallas de papel.",
            "<b>Sirve calientes.</b> Deja enfriar un par de minutos — el relleno está al rojo vivo. Sirve con kétchup, mayonesa de ajo, o cómelas naturales. Están mejores al momento de salir del aceite.",
        ],
        "tips_h2": "Consejos para Papa Rellena Perfecta",
        "tips": [
            "<b>Enfría el relleno completely.</b> Este es el consejo más importante. Si el relleno está siquiera ligeramente tibio al formar las bolas, la papa se ablandará y la bola se deshará en el aceite. Refrigera el relleno 20 minutos si hace falta.",
            "<b>Machaca las papas a fondo.</b> Cualquier grumo en la papa creará puntos débiles donde la bola puede agrietarse al freírse. Machaca hasta completely suave, o pásalas por un prensapapas.",
            "<b>No las hagas muy grandes.</b> Tamaño pelota de tenis es el punto ideal. Las bolas más grandes son más difíciles de freír parejo y pueden explotar en el aceite. Las pequeñas se sobre-cocinan antes de que el relleno se caliente.",
            "<b>Mantén la temperatura del aceite.</b> Si el aceite baja de 350°F, el empanizado absorbe demasiado aceite y queda grasoso. Fríe en tandas pequeñas para mantener la temperatura estable.",
        ],
        "faqs": [
            {"q": "¿Puedo hornear la papa rellena en vez de freírla?", "a": "Puedes hornearlas a 400°F por 25 minutos, volteando a mitad de camino. Cepilla o rocía con aceite para ayudar a que el exterior se dore. No quedarán tan doradas ni crujientes como las fritas, pero seguirán sabiendo bien. Para la verdadera experiencia de papa rellena, freír es el camino."},
            {"q": "¿Puedo usar camotes en vez de papas regulares?", "a": "Los camotes pueden funcionar, pero son mucho más húmedos y almidonados que las papas regulares. Necesitarás cocinarlos más tiempo para evaporar humedad, y el dulzor natural contrastará con el relleno savory de carne. Es un giro interesante, pero es otro plato. Para papa rellena traditional, quédate con Russet o Yukon Gold."},
            {"q": "¿Puedo hacer papa rellena con anticipación?", "a": "Sí — forma las bolas, empanízalas y refrigera hasta 24 horas antes de freír. También puedes congelarlas hasta 3 meses. Fríelas directamente congeladas, añadiendo 1-2 minutos extra al tiempo. No descongeles las papas rellenas congeladas antes — se desharán."},
        ],
    },
}
