# -*- coding: utf-8 -*-
"""ES translations batch 4/5: pastelillos, pinchos, quesitos, sancocho, sofrito."""

DATA = {
    "pastelillos": {
        "title": "Pastelillos de Carne — Receta Puertorriqueña de Empanadas de Carne",
        "desc": "Aprende a hacer pastelillos de carne, los bolsillos de masa dorados y hojaldrados de Puerto Rico con carne savory, pasas y alcaparrado.",
        "eyebrow": "Frituras",
        "trust": ["50 minutos", "Media"],
        "serves": "Rinde 15 pastelillos:",
        "intro": "Los <b>pastelillos de carne</b> son bolsillos de masa dorados y hojaldrados — el snack más querido de Puerto Rico. La combinación de carne savory, pasas dulces y alcaparrado salobre es únicamente boricua. Mientras las empanadillas son la prima frita e inflada, los pastelillos toman otro enfoque — típicamente se hornean (aunque freírlos también es común), usando una masa más delgada y hojaldrada que se desmorona al morderla. El relleno es una mezcla tipo picadillo de carne molida, sofrito, sazón, salsa de tomate, pasas y alcaparrado (alcaparras y aceitunas). Esa combinación de dulce, savory y salobre es lo que hace los pastelillos distintivamente puertorriqueños. Los encontrarás en cada panadería, cafetería y reunión familiar de la isla, y están igual de buenos a temperatura ambiente que recién salidos del horno.",
        "whatis": [
            "Los pastelillos de carne son turnovers horneados (o fritos) rellenos de una mezcla savory de carne molida. A diferencia de la masa de empanadilla, más gruesa y suave, la masa del pastelillo es más delgada y hojaldrada — más parecida a una corteza de pie o pasta de hojaldre. El relleno es la misma base de picadillo usada en las empanadillas, pero con dos adiciones clave: pasas y alcaparrado. Las pasas añaden bolsillos de dulzor que contrastan bellamente con la carne savory, mientras el alcaparrado (una mezcla de alcaparras y aceitunas verdes) aporta toques salobres de sabor. Los pastelillos se cepillan con huevo batido antes de hornearse, lo que les da ese acabado dorado y brillante característico. Son un básico de las panaderías puertorriqueñas y a menudo se sirven junto a un café con leche para el desayuno o como merienda. Hacerlos en casa es sorprendentemente directo — la parte más difícil es esperar a que se enfríen lo suficiente para comerlos.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="1" data-unit="lb">1 libra</span> de carne molida</b> — 80/20 regular para el mejor sabor y humedad.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4</span> taza de sofrito</b> — casero o comprado. La base aromática.',
            '<b><span class="ing-qty" data-base="1" data-unit="packet">1</span> sobrecito de sazón con culantro y achiote</b> — para color y profundidad.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2</span> taza de salsa de tomate</b> — añade humedad y un toque de dulzor.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4</span> taza de pasas</b> — el contraste dulce que hace únicos los pastelillos. Hidrátalas en agua tibia 5 minutos si están secas.',
            '<b><span class="ing-qty" data-base="2" data-unit="tbsp">2 cucharadas</span> de alcaparrado</b> — alcaparras y aceitunas picadas juntas. Encuéntralo en el pasillo latino o pica tu propia mezcla.',
            '<b><span class="ing-qty" data-base="15" data-unit="pastelillo">15</span> discos (o corteza de pie)</b> — más delgados que los discos de empanada. Si usas corteza de pie, estírala fina y corta en rondas de 5 pulgadas.',
            '<b><span class="ing-qty" data-base="1">1</span> huevo, batido</b> — para el baño de huevo. Da a los pastelillos su acabado dorado y brillante.',
        ],
        "swaps_h3": None,
        "swaps": [],
        "steps": [
            "<b>Dora la carne.</b> Cocina la carne molida en un sartén a fuego medio-alto, desmenuzándola con una cuchara. Escurre la grasa una vez dorada por completo.",
            "<b>Construye el relleno.</b> Añade el sofrito, el sazón, la salsa de tomate, las pasas y el alcaparrado a la carne. Revuelve bien y cocina 5 minutos. Prueba y ajusta el sazonado. Transfiere a un plato y deja enfriar completely — el relleno tibio hará la masa pasable.",
            "<b>Rellena y sella.</b> Precalienta el horno a 400°F. Forra una bandeja con papel pergamino. Coloca unas 1.5 cucharadas de relleno en cada disco. Dobla la masa en media luna y presiona los bordes firmemente con un tenedor para sellar.",
            "<b>Baño de huevo y hornea.</b> Cepilla cada pastelillo generosamente con huevo batido. Esto es lo que les da ese hermoso color dorado. Hornea 15-18 minutos hasta que la masa esté inflada y dorada profunda.",
            "<b>Enfría y sirve.</b> Déjalos reposar en la bandeja 5 minutos antes de transferirlos a una rejilla. Están mejores tibios, pero honestamente, también deliciosos a temperatura ambiente. Sirve con un chorrito de kétchup o mayonesa — la manera puertorriqueña.",
        ],
        "tips_h2": "Consejos para Pastelillos Perfectos",
        "tips": [
            "<b>Enfría el relleno completely.</b> Es la misma regla que las empanadillas. El relleno tibio crea vapor, que vuelve la masa pasable y hace que reviente en el horno.",
            "<b>No sobre-rellenes.</b> 1.5 cucharadas es el punto ideal. Más relleno significa que los bordes no sellarán bien y el relleno se escapará durante el horneado.",
            "<b>Usa discos de pastelillo, no discos de empanada.</b> Los discos de pastelillo son más delgados y hojaldrados. Si solo encuentras discos de empanada, estíralos más delgados con un rodillo antes de usar.",
            "<b>El baño de huevo es esencial.</b> Sin él, los pastelillos se verán pálidos y apagados. El huevo les da ese brillo dorado de panadería.",
        ],
        "faqs": [
            {"q": "¿Horneo o frío los pastelillos?", "a": "Ambos métodos funcionan y cada uno tiene sus fans. Hornear te da una masa más hojaldrada y seca, menos grasosa. Freír te da una costra más crujiente e inflada, más parecida a la empanadilla. La receta de arriba es para hornear, pero puedes freírlos a 350°F por 3-4 minutos por lado si prefieres la experiencia de fritura. De cualquier manera, son deliciosos."},
            {"q": "¿Qué discos debo usar?", "a": "Los discos de pastelillo son más delgados que los de empanada — están diseñados específicamente para pastelería horneada. Los encuentras congelados en supermercados latinos. Si no los encuentras, la masa de hojaldre congelada o la corteza de pie funcionan bien. Estírala fina y corta en círculos de 5 pulgadas. La diferencia clave es que la masa de pastelillo está hecha para ser hojaldrada, no masticable."},
            {"q": "¿Puedo hacer pastelillos con anticipación?", "a": "Sí. Puedes armar los pastelillos y congelarlos antes de hornear — colócalos en una bandeja, congela hasta solidificar, luego pásalos a una bolsa de congelador. Durán hasta 3 meses. Hornea directamente congelados a 400°F por 18-22 minutos (añade unos minutos extra porque están congelados). También puedes hornearlos primero y refrigerarlos hasta 4 días — recalienta en horno a 350°F por 8-10 minutos para recuperar el crujido."},
        ],
    },
    "pinchos": {
        "title": "Pinchos — Receta Puertorriqueña de Brochetas a la Parrilla",
        "desc": "Aprende a hacer pinchos, las legendarias brochetas puertorriqueñas — pollo o cerdo marinado, carbonizado y jugoso.",
        "eyebrow": "Platos principales",
        "trust": ["30 min + marinado", "Fácil"],
        "serves": "Rinde 4 porciones:",
        "intro": "Los <b>pinchos</b> son brochetas puertorriqueñas a la parrilla — la comida de playa, la comida de fiesta, la comida de 'no tengo ganas de cocinar'. Cada kiosco y vendedor ambulante tiene su propia receta de marinado. Son las brochetas cuyo olor flota desde cada fritura de la isla — trozos de pollo o cerdo jugoso, ensartados en palitos, asados hasta carbonizar, y terminados con una pincelada de mantequilla de ajo. En Puerto Rico, los pinchos son sinónimo de reunión. Están en cada barbacoa de patio trasero, cada día de playa, cada festival. El marinado es simple pero potente: aceite de oliva, ajo, orégano, vinagre y sazón. La carne lo absorbe todo, y luego la parrilla añade ese carbón ahumado que los hace irresistibles. Ya sea carbón o el broiler de tu horno, los pinchos entregan esa inconfundible experiencia de comida callejera boricua.",
        "whatis": [
            "Los pinchos (a veces escritos 'pinchos') son brochetas de carne puertorriqueñas, similares en concepto a los kabobs pero distintivamente boricuas en sabor. La palabra viene del español 'pinchar'. Típicamente llevan muslos de pollo o lomo de cerdo cortados en trozos, marinados en una mezcla a la garlicky y herbácea, y ensartados en palitos de madera. El marinado es la estrella: aceite de oliva, ajo picado, orégano seco, vinagre y un sobrecito de sazón le dan a la carne un perfil profundamente savory, ligeramente ácido y bellamente coloreado. Tras asar o hacer broil, reciben una pincelada final de mantequilla de ajo — porque en Puerto Rico, la mantequilla lo mejora todo. Los pinchos se sirven como plato principal, snack o aperitivo de fiesta. Combinan perfecto con tostones, arroz, o solos.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="1.5" data-unit="lbs">1.5 libras</span> de muslos de pollo o cerdo</b> — deshuesados, sin piel. Los muslos quedan más jugosos que la pechuga. El lomo de cerdo funciona genial también.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4 taza</span> de aceite de oliva</b> — la base del marinado. Ayuda a distribuir los sabores y evita que se pegue.',
            '<b><span class="ing-qty" data-base="3" data-unit="cloves">3 dientes</span> de ajo, picados</b> — el ajo fresco no es negociable. Cuanto más, mejor.',
            '<b><span class="ing-qty" data-base="1" data-unit="tbsp">1 cucharada</span> de orégano seco</b> — la columna terrosa y ligeramente amarga del marinado.',
            '<b><span class="ing-qty" data-base="1" data-unit="tbsp">1 cucharada</span> de vinagre</b> — blanco o de manzana. Ablanda la carne y añade brillo.',
            '<b><span class="ing-qty" data-base="1" data-unit="packet">1 sobrecito</span> de sazón con culantro y achiote</b> — para ese color y sabor característicos.',
            '<b>Sal y pimienta al gusto</b>',
            '<b>Palitos de madera, remojados en agua 30 minutos</b> — evita que se quemen en la parrilla.',
        ],
        "swaps_h3": None,
        "swaps": [],
        "steps": [
            "<b>Corta y marina la carne.</b> Corta el pollo o cerdo en trozos de 1.5 pulgadas. Coloca en un bol grande y añade el aceite de oliva, el ajo picado, el orégano, el vinagre, el sazón, la sal y la pimienta. Revuelve hasta cubrir cada pieza. Cubre y refrigera al menos 1 hora — toda la noche es aún mejor.",
            "<b>Ensarta en los palitos.</b> Saca la carne del marinado y ensarta en palitos de madera remojados. Deja un pequeño espacio entre piezas para que el calor circule parejo. No las aprietes demasiado — el flujo de aire es lo que da el carbón.",
            "<b>A la parrilla o broil.</b> Calienta la parrilla a fuego medio-alto (o el broiler del horno a alta). Cocina los pinchos 4-5 minutos por lado hasta carbonizar en los bordes y cocinar por dentro. La temperatura interna debe llegar a 165°F para pollo o 145°F para cerdo.",
            "<b>Pincela con mantequilla de ajo.</b> En cuanto los pinchos salgan del calor, cepíllalos generosamente con mantequilla de ajo derretida. La mantequilla se funde en las grietas carbonizadas y añade un acabado rico que eleva toda la brocheta. Sirve de inmediato.",
        ],
        "tips_h2": "Consejos para Pinchos Perfectos",
        "tips": [
            "<b>Marina más tiempo.</b> Una hora es el mínimo, pero 4 horas o toda la noche marcan una diferencia enorme. El vinagre y la sal trabajan para ablandar la carne mientras el ajo y el orégano penetran cada fibra.",
            "<b>Usa muslos de pollo.</b> Tienen más grasa que la pechuga, lo que significa más sabor y más humedad. También son más indulgentes en la parrilla — más difíciles de sobre-cocinar.",
            "<b>Remoja los palitos.</b> Los palitos de madera se queman y rompen si van a la parrilla secos. Remójalos en agua al menos 30 minutos antes de ensartar.",
            "<b>No te saltes la mantequilla de ajo.</b> Es el toque final que separa los buenos pinchos de los geniales. Derrite mantequilla con un diente de ajo machacado y pincela mientras la carne aún chisporrotea.",
        ],
        "faqs": [
            {"q": "¿Qué carne funciona mejor para pinchos?", "a": "Los muslos de pollo son la elección más popular — se mantienen jugosos en la parrilla y absorben el marinado bellamente. El lomo o paleta de cerdo es la segunda más común. También puedes usar res (sirloin o flap) pero es menos tradicional. Evita la pechuga de pollo — se seca demasiado rápido sobre calor directo."},
            {"q": "¿Cuánto tiempo debo marinar la carne?", "a": "Al menos 1 hora para un sabor base. Para mejores resultados, marina 4-8 horas en el refrigerador. Toda la noche es ideal — el ajo y el orégano realmente penetran. Puedes llegar hasta 24 horas, pero más allá de eso el vinagre empieza a descomponer demasiado la textura de la carne."},
            {"q": "¿Puedo usar el horno en vez de la parrilla?", "a": "Sí — pon el horno en broil alto y coloca la rejilla a unas 6 pulgadas de la fuente de calor. Coloca los pinchos en una bandeja forrada con aluminio y haz broil 4-5 minutos por lado. Seguirás obteniendo un buen carbonizado en los bordes. Para color extra, puedes terminarlos bajo el broiler un minuto adicional."},
        ],
    },
    "quesitos": {
        "title": "Quesitos — Receta Puertorriqueña de Pastelillos de Queso Crema",
        "desc": "Aprende a hacer quesitos, pastelillos de hojaldre rellenos de queso crema de Puerto Rico. El básico de panadería que desaparece en un bocado.",
        "eyebrow": "Postres",
        "trust": ["30 minutos", "Fácil"],
        "serves": "Rinde 12 pastelillos:",
        "intro": "Los <b>quesitos</b> son pastelillos de hojaldre rellenos de queso crema — el básico de panadería que desaparece en un bocado. Cada panadería de Puerto Rico tiene una bandeja de estos pastelillos dorados espolvoreados de azúcar, y suelen ser lo primero en desaparecer. Entra a cualquier panadería de la isla y los verás alineados junto a las mallorcas y ensaimadas: pequeños triángulos de hojaldre escamado envueltos alrededor de una bolita de queso crema dulce, horneados hasta dorar y cubiertos con una capa brillante de azúcar. Son simples, son rápidos, y son peligrosamente adictivos. Comes uno y de inmediato buscas otro. Esta receta usa masa de hojaldre comprada — porque hasta abuela aprobaría ese atajo — y entrega un resultado que rivaliza con cualquier cosa de la panadería.",
        "whatis": [
            "Los quesitos (literalmente 'quesitos') son pequeños pastelillos hechos de masa de hojaldre rellena de una mezcla de queso crema endulzado. Se doblan en triángulos, se cepillan con huevo batido, se espolvorean con azúcar y se hornean hasta inflarse en bolsillos dorados y escamados. El nombre es un poco engañoso — contienen queso crema, no queso, pero el relleno de queso dulce es la estrella del show.",
            "Encontrarás quesitos en cada panadería puertorriqueña, usualmente en una vitrina de cristal junto a los otros pastelillos. Son un artículo de desayuno, una merienda de tarde y un postre — básicamente, no hay momento incorrecto para comer uno. La combinación de hojaldre que se desmorona y relleno suave y dulce de queso crema es una de esas parejas perfectas que no necesita mejoras.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="1" data-unit="package">1</span> paquete de masa de hojaldre (2 láminas)</b> — descongelada pero aún fría. Pepperidge Farm o cualquier marca toda-mantequilla funciona.',
            '<b><span class="ing-qty" data-base="8" data-unit="oz">8 oz</span> de queso crema, ablandado</b> — entero para el mejor sabor y textura.',
            '<b><span class="ing-qty" data-base="0.333" data-unit="cup">1/3 taza</span> de azúcar</b> — endulza el relleno sin volverlo empalagoso.',
            '<b><span class="ing-qty" data-base="1" data-unit="teaspoon">1 cucharadita</span> de extracto de vainilla</b> — redondea el sabor del queso crema.',
            '<b><span class="ing-qty" data-base="1">1</span> huevo, batido</b> — para el baño de huevo que les da su brillo dorado.',
            '<b>Azúcar para espolvorear</b> — el azúcar gruesa se ve más bonita, pero la granulada regular funciona bien.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay masa de hojaldre?</b> La comprada es el estándar — hasta las mejores panaderías de Puerto Rico la usan. Pepperidge Farm está en todo supermercado. No intentes hacer hojaldre desde cero a menos que tengas una tarde libre y un rodillo.",
            "<b>¿Añadir guayaba?</b> Claro. Añade una cucharadita de pasta de guayaba encima del queso crema antes de doblar para la combinación de sabor puertorriqueña clásica.",
            "<b>¿Queso crema bajo en grasa?</b> Funciona, pero el relleno no será tan rico ni cremoso. El entero vale la pena aquí.",
        ],
        "steps": [
            "<b>Precalienta y prepara.</b> Precalienta el horno a 400°F. Forra una bandeja con papel pergamino. Deja descongelar la masa de hojaldre según las instrucciones del paquete — debe estar maleable pero aún fría.",
            "<b>Haz el relleno.</b> En un bol, bate el queso crema ablandado con el azúcar y la vainilla hasta suave y cremoso. Sin grumos — tómate el tiempo para hacerlo bien.",
            "<b>Corta la masa.</b> Desdobla cada lámina de hojaldre y corta en 6 cuadrados iguales — eso te da 12 en total. Un cortador de pizza lo hace rápido y limpio.",
            "<b>Rellena y dobla.</b> Coloca como una cucharada de relleno en el centro de cada cuadrado. Dobla cada cuadrado en diagonal para formar un triángulo. Presiona los bordes con un tenedor para sellar — esto también les da ese borde festoneado clásico.",
            "<b>Baño de huevo y azúcar.</b> Cepilla cada quesito generosamente con huevo batido. Espolvorea con azúcar — no seas tímido, esa costra de azúcar es parte de la magia.",
            "<b>Hornea 12-15 minutos.</b> Hornea hasta que se inflen y doren profundo. La masa debe estar crujiente y el relleno apenas cuajado. Deja enfriar 5 minutos antes de comer — si puedes esperar tanto.",
        ],
        "tips_h2": "Consejos para Quesitos Perfectos",
        "tips": [
            "<b>Mantén la masa fría.</b> El hojaldre tibio es una pesadilla para trabajar y no inflará bien. Si se vuelve pegajoso, devuélvelo a la nevera 10 minutos.",
            "<b>Sella bien.</b> Usa un tenedor para festonear los bordes firmemente. Si las costuras se abren al hornear, el relleno se escapa y pierdes ese centro cremoso.",
            "<b>No sobre-rellenes.</b> Una cucharada generosa es suficiente. Demasiado relleno revienta el hojaldre y crea un desastre en la bandeja.",
            "<b>Hornea hasta dorar de verdad.</b> Los quesitos pálidos están mal horneados y la masa quedará masticable en vez de escamada. Espera ese dorado profundo — vale el minuto extra.",
        ],
        "faqs": [
            {"q": "¿Hojaldre casero o comprado?", "a": "El comprado es el camino para quesitos. El hojaldre desde cero es un proyecto de varias horas que involucra laminado de mantequilla y control preciso de temperatura. El resultado es increíble, pero hasta la mayoría de las panaderías puertorriqueñas usan masa comercial. Pepperidge Farm o un hojaldre toda-mantequilla de la sección congelada te dará excelentes resultados."},
            {"q": "¿Puedo añadir guayaba al relleno?", "a": "Claro — la guayaba y el queso crema son una combinación puertorriqueña clásica. Coloca una rodajita o cucharadita de pasta de guayaba encima del relleno de queso crema antes de doblar. El dulzor de la guayaba combina perfecto con la acidez del queso crema. Algunas panaderías venden una versión 'quesito de guayaba' tan popular como la natural."},
            {"q": "¿Cómo guardo los quesitos sobrantes?", "a": "Los quesitos están mejores frescos, pero se conservan en recipiente hermético a temperatura ambiente por 2 días. Para refrescarlos, caliéntalos en horno a 350°F por 3-4 minutos — esto re-cruje la masa. Refrigerarlos vuelve el hojaldre pasable, así que temperatura ambiente es mejor para almacenaje corto. También puedes congelar quesitos crudos en una bandeja, luego pasarlos a una bolsa — hornea congelados, añadiendo 2-3 minutos extra."},
        ],
    },
    "sancocho": {
        "title": "Sancocho — Receta Puertorriqueña de Guiso de Siete Carnes",
        "desc": "Aprende a hacer sancocho, el guiso de consuelo supremo de Puerto Rico con carnes mixtas y tubérculos. Una receta de 2 horas que alimenta a toda la familia.",
        "eyebrow": "Platos principales",
        "trust": ["2 horas", "Media"],
        "serves": "Para 10 porciones:",
        "intro": "El <b>sancocho</b> es la sopa de consuelo suprema de Puerto Rico — un guiso contundente lleno de siete carnes y tubérculos que ha estado hirviendo en la estufa por horas. Es el plato que lo arregla todo: el frío, el desamor, la nostalgia, los malos días. Cada familia puertorriqueña tiene su versión, pasada de generación en generación con reglas específicas sobre qué carnes usar, cuánto hervir, y si el maíz va entero o en pedazos. El caldo es la estrella — un líquido profundo y rico que ha absorbido los sabores de la res, el cerdo, el pollo y cada tubérculo que encuentres en el supermercado latino. Bien hecho, un solo plato es una comida completa que te calienta de adentro hacia afuera. Esta receta se mantiene fiel al enfoque tradicional: carnes mixtas, tubérculos reales y suficiente caldo para una mesa de diez.",
        "whatis": [
            "El sancocho es un guiso espeso y contundente que existe por toda Latinoamérica y el Caribe, pero la versión puertorriqueña es distintiva. Se construye sobre una base de múltiples carnes — típicamente res, cerdo y pollo — cocinadas a fuego lento con una mezcla de tubérculos tropicales llamadas viandas. El caldo se desarrolla por una hora o más, mientras las carnes se deshacen y liberan su colágeno y sabor en el líquido, mientras los tubérculos absorben el fondo savory y espesan el guiso naturalmente.",
            "En Puerto Rico, el sancocho es más que una receta — es un ritual. Es lo que las familias hacen después de huracanes cuando la luz está apagada y la estufa de gas es la única fuente de calor. Es lo que hace abuela cuando toda la familia viene de visita. Es el plato que calienta una noche fría de montaña en Utuado o Jayuya. La combinación específica de tubérculos varía por región y preferencia familiar, pero lo esencial siempre está: yuca por su sedosidad almidonada, plátano por cuerpo, y maíz por dulzor. Algunas familias añaden calabaza, algunas plátanos verdes, y algunas insisten en cortes específicos de carne. Pero el alma del plato — carne, tubérculos, sofrito, tiempo — permanece igual.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="2" data-unit="lbs">2 libras</span> de carnes mixtas (res, cerdo, pollo)</b> — una combinación de piezas con hueso funciona mejor. Chuck de res, paleta de cerdo y muslos de pollo son cortes ideales.',
            '<b><span class="ing-qty" data-base="1" data-unit="green">1 plátano</span> verde, pelado y en cubos</b> — verde, no maduro. El plátano almidonado espesa el caldo y añade sustancia.',
            '<b><span class="ing-qty" data-base="2" data-unit="yuca">2 pedazos</span> de yuca</b> — raíz de casava, pelada y cortada en trozos de 2 pulgadas. Quita el hilo fibroso central.',
            '<b><span class="ing-qty" data-base="2" data-unit="name">2 pedazos</span> de ñame</b> — ñame blanco o amarillo, pelado y en cubos. Añade dulzor terroso al caldo.',
            '<b><span class="ing-qty" data-base="1" data-unit="corn">1 mazorca</span> de maíz, cortada en pedazos</b> — cada pedazo de unas 2 pulgadas. El maíz añade dulzor al caldo.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4 taza</span> de sofrito</b> — la base aromática que lo une todo.',
            '<b><span class="ing-qty" data-base="1" data-unit="packet">1 sobrecito</span> de sazón</b> — con culantro y achiote para color y profundidad.',
            '<b><span class="ing-qty" data-base="8" data-unit="cups">8 tazas</span> de agua</b> — suficiente para cubrir todo con espacio para los vegetales.',
            '<b>Sal y pimienta al gusto</b>',
            '<b>Cilantro fresco para decorar</b> — hojas rotas y tallos tiernos.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay yuca?</b> Las papas Yukon Gold son el sustituto más cercano — se deshacen similar y espesan el caldo. Usa la misma cantidad.",
            "<b>¿No hay plátano verde?</b> El plátano verde (banana verde) funciona como sustituto con textura ligeramente diferente. El plátano maduro volverá el guiso demasiado dulce.",
            "<b>¿No hay ñame?</b> Papa extra o chirivía pueden reemplazarlo. El sabor no será exactamente igual, pero el almidón cumple el mismo propósito.",
        ],
        "steps": [
            "<b>Dora las carnes.</b> Calienta una olla grande y pesada a fuego medio-alto. Añade las carnes mixtas en tandas y dora por todos lados. No satures la olla — quieres un buen sellado, no vapor. Retira y reserva.",
            "<b>Construye el caldo.</b> Devuelve las carnes a la olla y añade 8 tazas de agua. Lleva a un hervor rodante, luego desespuma cualquier espuma o impureza que suba a la superficie. Esto te da un caldo de sabor más limpio.",
            "<b>Añade la base de sabor.</b> Incorpora el sofrito y el sobrecito de sazón. Aquí es donde el caldo empieza a desarrollar su color y aroma característicos.",
            "<b>Añade los tubérculos.</b> Echa los cubos de plátano, yuca, ñame y los pedazos de maíz. La olla debe verse como una cosecha — colorida y rebosante. Lleva de vuelta a hervor suave.",
            "<b>Cocina bajo y lento.</b> Baja el fuego a medio-bajo y cocina destapado de 1 a 1.5 horas. Las carnes deben estar tiernas al tenedor y el caldo rico y espeso por los tubérculos almidonados deshaciéndose.",
            "<b>Sazona y sirve.</b> Prueba el caldo y ajusta con sal y pimienta — lo necesitará después de toda esa agua. Sirve en tazones hondos con arroz blanco al lado. Corona con cilantro fresco.",
        ],
        "tips_h2": "Consejos para un Sancocho Perfecto",
        "tips": [
            "<b>Dora las carnes primero.</b> Este paso construye la base de sabor. Un buen sellado añade profundidad al caldo que no obtienes solo hirviendo. No lo omitas.",
            "<b>Desespuma.</b> Tras añadir el agua y llevarlo a hervir, quita la espuma y grasa que sube a la superficie. Esto te da un caldo más limpio que se ve y sabe mejor.",
            "<b>No te apures con el hervor lento.</b> El sancocho necesita tiempo. El mínimo es 1 hora, pero 1.5 es mejor. Las carnes necesitan tiempo para ablandarse y los tubérculos para soltar su almidón al caldo.",
            "<b>Sazona al final.</b> El caldo reduce mientras hierve, concentrando la sal. Siempre prueba y ajusta al final en vez de sobre-salar al inicio.",
        ],
        "faqs": [
            {"q": "¿Qué carnes debo usar para el sancocho?", "a": "Tradicionalmente, el sancocho usa una mezcla de al menos tres carnes — res, cerdo y pollo. Chuck de res, paleta de cerdo y muslos de pollo funcionan mejor porque resisten el hervor largo y quedan tiernos. Algunas versiones añaden longaniza o jamón para extra ahumado. La variedad de carnes es lo que da al sancocho su caldo complejo y por capas."},
            {"q": "¿Qué tubérculos son esenciales?", "a": "Los innegociables son la yuca y el plátano verde. La yuca da al caldo su cuerpo sedoso y almidonado, y el plátano añade espesor y dulzor sutil. El ñame y el maíz son adiciones tradicionales que completan el guiso. Si solo encuentras dos, asegúrate de que sean yuca y plátano — esos definen la textura."},
            {"q": "¿Puedo hacer sancocho en slow cooker?", "a": "Sí, pero dora las carnes primero en la estufa para el mejor sabor. Transfiere todo al slow cooker y cocina en low 7-8 horas o high 4-5. Añade los tubérculos en las últimas 2 horas para que no se hagan puré. El caldo no será tan rico como en estufa, pero sigue delicioso."},
        ],
    },
    "sofrito": {
        "title": "Sofrito Casero — Receta de la Base de Sabor Puertorriqueña",
        "desc": "Haz sofrito puertorriqueño auténtico desde cero — recao, ajo, pimientos y hierbas licuados en la base de sabor esencial para cocinar boricua.",
        "eyebrow": "Bases y Salsas",
        "trust": ["20 minutos", "Fácil"],
        "serves": "Rinde 2 tazas:",
        "intro": "El <b>sofrito</b> es la base de sabor de la cocina puertorriqueña — una mezcla verde y fragante cargada de hierbas que entra en casi cada plato savory de la isla. Si el arroz con gandules es el plato nacional, el sofrito es el arma secreta detrás de él. Cada hogar puertorriqueño tiene su versión, pasada de generación en generación como una reliquia familiar. Algunas familias usan más recao que cilantro, algunas añaden ají dulce, y algunas juran por mortero y pilón sobre el procesador de alimentos. Pero el núcleo nunca cambia: <b>hierbas frescas + aromáticos + aceite = la base de todo</b>. Hacer sofrito desde cero toma 20 minutos y transforma tu cocina. Una vez tienes un lote en el congelador, estás a un cubito de empezar cualquier receta puertorriqueña. Esta receta es la que aprendí de mi familia — y la que cambió cómo cocino.",
        "whatis": [
            "El sofrito es la pasta verde aromática que forma la base de la cocina puertorriqueña. Piensa en él como el equivalente caribeño del mirepoix francés o el soffritto italiano, pero con giro tropical: recao (culantro), cilantro, ajo, cebolla y pimiento, licuados en una pasta que huele a hogar en el momento en que toca el aceite caliente.",
            "En Puerto Rico, el sofrito es innegociable. Es lo primero que va al sartén para el arroz con pollo, las habichuelas, el pastelón y prácticamente cada guiso, plato de arroz y receta de habichuelas de la isla. El ingrediente estrella es el recao (también llamado culantro o perejil chino), que tiene un sabor más fuerte y terroso que el cilantro regular. Combinado con ajo, cebolla, pimiento y cilantro, crea una base de sabor a la vez fresca, pungente y profundamente savory. Hacer un lote y congelarlo en porciones significa que siempre estás listo para cocinar puertorriqueño.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="1" data-unit="bunch">1 manojo</span> de recao (culantro)</b> — unas 15 hojas largas y aserradas. Esto NO es cilantro. El recao tiene un sabor más fuerte y pungente. Encuéntralo congelado en supermercados latinos, o usa cilantro de diente de sierra de mercados asiáticos.',
            '<b><span class="ing-qty" data-base="1" data-unit="large">1 pimiento</span> verde grande</b> — sin semillas y toscamente picado. El verde es tradicional; el rojo añade dulzor pero cambia el color.',
            '<b><span class="ing-qty" data-base="1" data-unit="medium">1 cebolla</span> mediana</b> — en cuartos. Cualquier color funciona — amarilla o blanca son el estándar.',
            '<b><span class="ing-qty" data-base="8" data-unit="cloves">8 dientes</span> de ajo</b> — pelados (sí, 8 — esto es cocina puertorriqueña, no francesa). Usa fresco, no pre-picado.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2 taza</span> de cilantro (coriandro fresco)</b> — con tallos para sabor extra. Los tallos tienen sabor más concentrado que las hojas.',
            '<b><span class="ing-qty" data-base="2" data-unit="tablespoons">2 cucharadas</span> de aceite de oliva</b> — ayuda a preservar el color y añade riqueza.',
            '<b><span class="ing-qty" data-base="1" data-unit="teaspoon">1 cucharadita</span> de sal</b> — realza todos los sabores y actúa como conservante suave.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>Recao congelado</b> — disponible en la mayoría de supermercados latinos del país. Es tu mejor opción. Descongela antes de usar.",
            "<b>Cilantro extra</b> — usa 1 taza de cilantro en vez de recao + cilantro. El sabor es más suave pero sigue funcionando para la mayoría de platos.",
            "<b>Cilantro de diente de sierra</b> — se encuentra en supermercados asiáticos e indios. Es la misma planta que el recao (Eryngium foetidum) y funciona perfectamente.",
            "<b>Ají dulce</b> — adición opcional para una base más dulce y compleja. Encuéntralo congelado en mercados latinos.",
        ],
        "steps": [
            "<b>Lava todo.</b> Enjuaga el recao, cilantro, pimiento y cebolla bajo agua fría. Seca con toallas de papel. Las hierbas mojadas volverán tu sofrito aguado.",
            "<b>Al procesador de alimentos.</b> Corta el pimiento y la cebolla en cuartos toscos. Añade el recao, pimiento, cebolla, ajo y cilantro al procesador. No añadas el aceite aún.",
            "<b>Pulsa, no licúes.</b> Pulsa 8-10 veces hasta que todo esté finamente picado pero aún veas pedacitos pequeños. Quieres <i>textura</i>, no sopa. Detente y raspa los lados una o dos veces.",
            "<b>Añade aceite y sal.</b> Vierte el aceite de oliva y espolvorea la sal. Pulsa 3-4 veces más solo para integrar. El aceite ayuda a preservar el verde brillante.",
            "<b>Guárdalo bien.</b> Transfiere a bandejas de cubitos de hielo para porciones individuales, o a frascos. Congela hasta 3 meses. Refrigera hasta 1 semana (se oscurecerá un poco pero sabrá igual de rico).",
        ],
        "tips_h2": "Consejos para un Sofrito Perfecto",
        "tips": [
            "<b>No sobre-proceses.</b> Si se vuelve sopa verde, fuiste demasiado lejos. Detente cuando aún veas pedacitos pequeños de cada ingrediente. La textura importa — quieres trocitos de ajo y pimiento, no un smoothie.",
            "<b>Usa recao fresco cuando puedas.</b> El congelado funciona genial, pero el recao fresco tiene un sabor más brillante y complejo. Si lo cultivas (es una planta resistente), nunca volverás atrás.",
            "<b>Congela en porciones.</b> Las bandejas de cubitos son perfectas — cada cubito son unas 2 cucharadas, suficiente para una receta. Sácalos, envíalos a una bolsa, y agarra un cubito cuando lo necesites.",
            "<b>No te saltes el ajo.</b> 8 dientes suena a mucho. No lo es. Esto es cocina puertorriqueña — el ajo es ingrediente primario, no un condimento.",
        ],
        "faqs": [
            {"q": "¿Qué hago si no encuentro recao (culantro)?", "a": "El recao congelado está disponible en la mayoría de supermercados latinos del país y es tu mejor opción. Si no lo encuentras, el cilantro de diente de sierra (en mercados asiáticos e indios) es la misma planta. Como último recurso, duplica el cilantro — el sabor será más suave pero seguirá funcionando para la mayoría de platos."},
            {"q": "¿Cuánto dura el sofrito casero?", "a": "En el refrigerador, el sofrito casero dura 5-7 días. Se oscurecerá un poco con el tiempo pero el sabor se mantiene fuerte. Para almacenaje más largo, congélalo — se conserva hasta 3 meses en el congelador. Las bandejas de cubitos son el mejor método para porcionar."},
            {"q": "¿Puedo congelar el sofrito?", "a": "Claro — congelar es como cada hogar puertorriqueño almacena el sofrito. Vierte en bandejas de cubitos, congela hasta solidificar, luego transfiere los cubitos a una bolsa de congelador. Cada cubito son unas 2 cucharadas, perfectas para empezar una receta. Durán hasta 3 meses y se descongelan en minutos en un sartén caliente."},
        ],
    },
}