# -*- coding: utf-8 -*-
"""ES translations batch 2/5: besitos-de-coco, cafe-con-leche, chocolate-caliente, chuletas, empanadillas."""

DATA = {
    "besitos-de-coco": {
        "title": "Besitos de Coco — Receta Puertorriqueña de Besos de Coco",
        "desc": "Aprende a hacer besitos de coco, los besos de coco puertorriqueños. Masticables, dulces e increíblemente simples.",
        "eyebrow": "Postres",
        "trust": ["25 minutos", "Fácil"],
        "serves": "Rinde 20 besitos:",
        "intro": "Los <b>besitos de coco</b> son macaroons de coco con forma de pequeños besos — masticables, dulces e increíblemente simples. El nombre significa 'pequeños besos de coco', y eso es exactamente lo que son. Cinco ingredientes, un bol, sin batidora, sin complicaciones. Mezclas, porcionas, horneas, y 15 minutos después tienes un plato de galletas de coco con bordes dorados que saben a tarde tropical. Aparecen en cada reunión navideña puertorriqueña, usualmente en una bandeja junto al tembleque y el flan. Algunos los mojan en chocolate, otros los dejan naturales, pero todos se los comen más rápido de lo que salen. Esta es una de esas recetas que demuestra que las mejores cosas son las más simples.",
        "whatis": [
            "Los besitos de coco son macaroons puertorriqueños de coco hechos solo con coco rallado endulzado, huevos, azúcar, vainilla y sal. A diferencia de los macarons franceses (a base de almendras y delicados), estos son montículos rústicos y libres de coco que se hornean masticables en el centro con bordes dorados ligeramente crujientes. No hay harina, no hay mantequilla, no hay técnica complicada — solo coco unido con huevo y horneado hasta que los bordes se caramelizan.",
            "Son un básico de las panaderías y mesas navideñas puertorriqueñas, apareciendo a menudo junto a quesitos, flan y tembleque como parte del despliegue de postres. La simplicidad es el punto — cuando tienes buen coco, no necesitas mucho más. Son naturalmente libres de gluten, lo que los hace del agrado de todos, incluyendo quienes tienen restricciones alimentarias.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="3" data-unit="cups">3 tazas</span> de coco rallado endulzado</b> — la bolsa estándar es de 14 oz, exactamente lo que necesitas.',
            '<b><span class="ing-qty" data-base="2" data-unit="eggs">2 huevos</span></b> — el aglutinante que mantiene todo unido.',
            '<b><span class="ing-qty" data-base="0.333" data-unit="cup">1/3 taza</span> de azúcar</b> — añade dulzor extra más allá del que aporta el coco.',
            '<b><span class="ing-qty" data-base="1" data-unit="teaspoon">1 cucharadita</span> de extracto de vainilla</b> — realza el sabor a coco.',
            '<b>Una pizca de sal</b> — balancea el dulzor e ilumina el coco.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿Coco endulzado o sin endulzar?</b> El endulzado es lo tradicional y da la mejor textura. Si usas sin endulzar, añade 2 cucharadas extra de azúcar.",
            "<b>¿Los quieres más masticables?</b> Hornea 1-2 minutos menos. Los centros quedarán más blandos, tipo malvavisco.",
            "<b>¿Los quieres más crujientes?</b> Hornea 2-3 minutos extra hasta que las tapas estén doradas. Quedarán crocantes por completo.",
        ],
        "steps": [
            "<b>Precalienta el horno.</b> Pon el horno a 325°F. Forra una bandeja con papel pergamino — no te saltes el papel, se pegarán sin él.",
            "<b>Mezcla todo.</b> En un bol grande, combina el coco rallado, los huevos, el azúcar, la vainilla y la sal. Revuelve con un tenedor hasta que todo esté humectado uniformemente. No hay técnica especial aquí — solo mezcla hasta integrar.",
            "<b>Porciona en la bandeja.</b> Usa una cucharada o cuchara porcionadora pequeña para hacer montículos de la mezcla sobre la bandeja preparada. Espacialos unas 2 pulgadas — no se extienden mucho, pero necesitan su espacio.",
            "<b>Hornea 12-15 minutos.</b> Hornea hasta que los bordes estén dorados y las tapas ligeramente tostadas. Los centros deben seguir blandos — se firman al enfriar. No sobre-hornees o perderán el centro masticable.",
            "<b>Enfría completamente.</b> Deja enfriar los besitos en la bandeja al menos 5 minutos, luego transfiérelos a una rejilla. Siguen cuajando al enfriarse. Cómelos a temperatura ambiente para la mejor textura.",
        ],
        "tips_h2": "Consejos para Besitos de Coco Perfectos",
        "tips": [
            "<b>Usa papel pergamino.</b> Se soldarán a una bandeja sin engrasar. Pergamino o tapete de silicona es obligatorio.",
            "<b>Vigila los bordes.</b> Los bordes dorados son el indicador de que están listos. Las tapas pueden verse pálidas — está bien. Los bordes dicen la verdad.",
            "<b>No sobre-mezcles.</b> Solo necesitas que el hovo cubra el coco. Trabajar demasiado la mezcla puede volver las galletas densas en vez de masticables.",
            "<b>Deja enfriar.</b> Son frágiles calientes y se desharán. Dales unos minutos en la bandeja antes de moverlos.",
        ],
        "faqs": [
            {"q": "¿Puedo hacerlos masticables o crujientes?", "a": "Ambos son posibles con la misma receta. Para besitos masticables, hornea 12 minutos y sácalos cuando los bordes apenas estén dorados — los centros estarán blandos y cuajarán al enfriar. Para crujientes, hornea 15-16 minutos hasta que las tapas estén doradas por completo. La versión clásica es masticable en el centro con bordes crujientes — apunta al punto ideal de 13-14 minutos."},
            {"q": "¿Puedo usar coco sin endulzar?", "a": "Sí, pero añade 2 cucharadas extra de azúcar para compensar. El coco sin endulzar también suele ser más seco, así que la textura puede ser ligeramente menos masticable. El coco rallado endulzado es el estándar para esta receta porque aporta tanto el dulzor como la humedad que los macaroons necesitan."},
            {"q": "¿Puedo mojarlos en chocolate?", "a": "Claro — los besitos bañados en chocolate son una variación popular. Una vez las galletas estén completely frías, moja las bases en chocolate oscuro o semi-amargo derretido y colócalas sobre pergamino para que cuaje. Algunos rocían chocolate por encima en su lugar. De cualquier forma, la combinación chocolate-coco es increíble."},
        ],
    },
    "cafe-con-leche": {
        "title": "Café con Leche — Receta Puertorriqueña de Café con Leche",
        "desc": "Aprende a hacer café con leche, el querido café puertorriqueño fuerte, dulce y cremoso — el ritual que inicia cada mañana en la isla.",
        "eyebrow": "Bebidas",
        "trust": ["10 minutos", "Fácil"],
        "serves": "Rinde 2 porciones:",
        "intro": "El café con leche es más que café en Puerto Rico — es un ritual. Fuerte, dulce y cremoso, así comienza cada mañana en la isla. El debate sobre la proporción perfecta es eterno. A algunos les gusta mitad café, mitad leche. Otros prefieren un golpe de café más fuerte con solo un chorrito de leche. Y el azúcar — siempre el azúcar — es innegociable para la mayoría de los boricuas. El café puertorriqueño es famoso por su sabor suave y achocolatado, y cuando lo combinas con leche entera caliente y una cucharada generosa de azúcar, obtienes algo que trasciende la suma de sus partes. Es el café que bebes recostado en la mesada de la cocina de abuela, mirando salir el sol por la ventana. Es el café que impulsa el commute matutino en San Juan y el descanso vespertino en las montañas. Es simple, perfecto y profundamente puertorriqueño.",
        "whatis": [
            "Café con leche significa literalmente 'coffee with milk', pero en Puerto Rico es mucho más de lo que esa traducción sugiere. Los granos de café puertorriqueños — cultivados en las regiones montañosas de la isla, particularmente alrededor de Utuado y Jayuya — son conocidos por ser suaves, delicados y naturalmente dulces con notas achocolatadas y de nuez. Cuando se preparan fuertes y se combinan con leche entera caliente, el resultado es una bebida rica y aterciopelada a años luz de un café de goteo aguada con un chorrito de leche. La cafetera tradicional puertorriqueña (una olla estilo espresso de estufa) prepara el café fuerte y concentrado, lo cual es esencial para la bebida. Necesitas esa intensidad para enfrentarse a la leche y el azúcar. En Puerto Rico, el café con leche se sirve típicamente en tacitas — no es un tazón gigante que sorbes por una hora. Es un shot rápido y potente de consuelo que combina perfectamente con un pan de mallorca, un pastelillo, o simplemente buena conversación.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4 taza</span> de café de tueste oscuro</b> — preferiblemente granos puertorriqueños. Café Yaucono, Alto Grande o Café Crema son las marcas clásicas. Usa cualquier tueste oscuro si no hay granos puertorriqueños disponibles.',
            '<b><span class="ing-qty" data-base="2" data-unit="cups">2 tazas</span> de agua</b> — el agua filtrada marca diferencia en el sabor.',
            '<b><span class="ing-qty" data-base="1" data-unit="cup">1 taza</span> de leche entera</b> — la leche entera da el resultado más cremoso. La 2% funciona pero no será tan rica. La leche de avena es una alternativa vegetal decente.',
            '<b>2-3 cdas de azúcar</b> — ajusta al gusto. A la mayoría de los puertorriqueños les gusta dulce. El azúcar blanca es traditional, pero algunos usan pilón (azúcar de caña cruda).',
        ],
        "swaps_h3": None,
        "swaps": [],
        "steps": [
            "<b>Prepara el café.</b> Usa una cafetera puertorriqueña, moka, prensa francesa o máquina de espresso. La clave es prepararlo fuerte — quieres un café concentrado y audaz que pueda enfrentarse a la leche. Si usas cafetera, llena la cámara inferior con agua y el filtro con café de tueste oscuro molido fino.",
            "<b>Calienta la leche.</b> Mientras se prepara el café, vierte la leche en una olla pequeña y calienta a fuego medio hasta que humee. No dejes que hierva — la quieres caliente y ligeramente espumosa, no escaldada. Si tienes vaporizador de leche, dale una espumada rápida para extra cremosidad.",
            "<b>Combina y endulza.</b> Vierte el café fuerte en dos tazas, llenando cada una a la mitad. Cubre con la leche caliente. Añade azúcar al gusto — empieza con 2 cucharadas por taza y ajusta desde ahí. Revuelve bien y sirve de inmediato.",
        ],
        "tips_h2": "Consejos para el Café con Leche Perfecto",
        "tips": [
            "<b>Prepáralo fuerte.</b> El café debe estar concentrado y audaz. Si tu café sabe aguado tras añadir la leche, necesitas más café o prepararlo más tiempo. Una cafetera puertorriqueña o moka es ideal para esto.",
            "<b>Usa leche entera.</b> La grasa de la leche entera crea esa textura cremosa característica. La descremada saberá ligera y aguada. Si eres intolerante a la lactosa, la leche de avena es la mejor alternativa — tiene una cremosidad similar.",
            "<b>No te saltes el azúcar.</b> Sí, puedes hacerlo sin azúcar, pero te perderías una parte central de la experiencia. El azúcar balancea el amargor del café fuerte y realza el dulzor natural de la leche.",
            "<b>Sirvelo caliente.</b> El café con leche está mejor fresco y caliente. La leche empieza a separarse y el café se enfría rápido, así que vierte y sirve de inmediato.",
        ],
        "faqs": [
            {"q": "¿Qué marca de café es la más auténtica?", "a": "Café Yaucono, Alto Grande y Café Crema son las tres marcas clásicas puertorriqueñas. Yaucono es la más disponible — la encuentras en Walmart, Target y la mayoría de supermercados latinos. Alto Grande es un poco más premium y tiene un sabor más suave, menos amargo. Café Yaucono es la con la que creció la mayoría de los hogares puertorriqueños."},
            {"q": "¿Puedo usar café instantáneo?", "a": "Técnicamente sí, pero no sabrá igual. La fuerza y el sabor del café con leche dependen de café bien preparado y concentrado. El instantáneo tiende a ser más ligero y amargo sin las notas suaves y achocolatadas que aportan los granos puertorriqueños. En apuros, usa 2-3 cucharaditas de espresso instantáneo en polvo en agua caliente — se acerca más que el café instantáneo regular."},
            {"q": "¿El café con leche debe ser dulce o amargo?", "a": "En Puerto Rico, dulce es el estándar. La mayoría de los boricuas toman su café con leche con 2-3 cucharadas de azúcar por taza. No se trata de enmascarar el café — el azúcar de hecho realza las notas suaves y achocolatadas de los granos puertorriqueños y balancea la intensidad del brebaje fuerte. Dicho esto, ajusta a tu propio gusto. Empieza con 1-2 cucharadas y añade más si lo prefieres más dulce."},
        ],
    },
    "chocolate-caliente": {
        "title": "Chocolate Caliente Boricua — Receta Puertorriqueña de Chocolate Caliente",
        "desc": "Aprende a hacer chocolate caliente boricua, chocolate caliente puertorriqueño con chocolate real y canela. Espeso, rico y listo en 15 minutos.",
        "eyebrow": "Bebidas",
        "trust": ["15 minutos", "Fácil"],
        "serves": "Para 4 porciones:",
        "intro": "El <b>chocolate caliente boricua</b> es el chocolate caliente puertorriqueño — y nada como esas sobrecitas aguadas que quizás conoces. Esto es lo real: espeso, rico, con canela, y hecho con chocolate de verdad derretido en leche entera hasta ser prácticamente un postre en taza. En Puerto Rico, el chocolate caliente es lo que bebes en Nochebuena después de la piñata, lo que hace abuela cuando alguien está resfriado, y lo que te calienta en una tarde fresca de montaña en Adjuntas o Jayuya. El chocolate se derrite en la leche mientras se calienta, creando una bebida a medio camino entre el cocoa caliente y la ganache líquida. Añade una ramita de canela para revolver, y tienes el tipo de bebida que te hace cerrar los ojos en el primer sorbo y olvidarte de todo lo demás.",
        "whatis": [
            "El chocolate caliente boricua es la versión puertorriqueña del chocolate caliente — hecho con chocolate real (no cacao en polvo), leche entera, azúcar y canela. El enfoque tradicional puertorriqueño usa tabletas de chocolate mexicano como Ibarra o Abuelita, que vienen premezcladas con azúcar y canela. Estas tabletas se disuelven en leche caliente y crean una bebida espesa, fragante y profundamente satisfactoria. Si no encuentras chocolate mexicano, una combinación de buen chocolate oscuro y canela molida funciona casi igual de bien.",
            "Lo que distingue al chocolate caliente puertorriqueño de la versión americana es la riqueza. Se hace con chocolate real derretido en leche, no polvo mezclado en agua. El resultado es una bebida más cercana al postre líquido que a una bebida ligera. Algunas familias añaden una pizca de chile en polvo para picante, algunas lo baten hasta espumarlo con un molinillo de madera, y otras lo sirven con mallorcas o quesitos para mojar. Pero el núcleo — chocolate real, leche real, canela real — permanece igual. En Puerto Rico, el chocolate caliente no es un antojo de temporada. Es un consuelo de todo el año que resulta extra popular durante las fiestas.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="4" data-unit="oz">4 oz</span> de chocolate mexicano</b> — tabletas Ibarra o Abuelita, que ya traen azúcar y canela mezcladas. Si no las encuentras, usa 4 oz de chocolate oscuro (70% cacao) + 1/2 cdta de canela molida.',
            '<b>4 tazas de leche entera</b> — la riqueza entera es lo que hace especial esta bebida. La 2% funciona en apuros, pero no uses descremada.',
            '<b>1/4 taza de azúcar</b> — ajusta al gusto. El chocolate mexicano ya viene endulzado, así que empieza con menos si usas Ibarra o Abuelita.',
            '<b>1 cucharadita de extracto de vainilla</b> — redondea el sabor a chocolate y añade calidez.',
            '<b>Una pizca de sal</b> — realza el sabor a chocolate y balancea el dulzor.',
            '<b>Ramitas de canela para servir</b> — una por taza. Úsalas para revolver mientras bebes — la canela infunde el chocolate conforme reposa.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay chocolate mexicano?</b> Usa 4 oz de buen chocolate oscuro (60-70% cacao) + 1/2 cdta de canela molida + una cucharada extra de azúcar. No tendrá la textura exacta, pero el sabor se acerca.",
            "<b>¿No hay leche entera?</b> La leche de avena es el mejor sustituto sin lácteos — es cremosa y de sabor neutro. La de almendras funciona pero hace una bebida más ligera. La de coco la hace más rica pero aporta sabor a coco.",
            "<b>¿La quieres más espesa?</b> Añade 1 cucharada de maicena disuelta en un chorrito de leche fría a la leche calentándose. Bate constantemente mientras espesa.",
        ],
        "steps": [
            "<b>Calienta la leche.</b> Vierte la leche en una olla mediana y calienta a fuego medio hasta que humea y se formen pequeñas burbujas en los bordes. No dejes que hierva — hervir puede escaldar la leche y cambiar la textura.",
            "<b>Derrite el chocolate.</b> Rompe la tableta de chocolate mexicano en pedazos y añádela a la leche caliente. Revuelve continuamente con batidor o cuchara de madera hasta que el chocolate se derrita por completo y la leche tome un marrón profundo y rico.",
            "<b>Endulza y saboriza.</b> Añade el azúcar, la vainilla y la pizca de sal. Bate vigorosamente por un minuto — esto incorpora aire y crea la espuma superior que los puertorriqueños aman. Prueba y ajusta el azúcar si hace falta.",
            "<b>Sirve con ramita de canela.</b> Vierte en tazas — la espuma superior debe estar espesa e invitante. Deja caer una ramita de canela en cada taza. Revuelve con la ramita mientras bebes; sigue infusionando el chocolate con calidez de canela.",
        ],
        "tips_h2": "Consejos para un Chocolate Caliente Perfecto",
        "tips": [
            "<b>No hiervas la leche.</b> La leche escaldada desarrolla una piel encima y un sabor extraño. Caliéntala hasta que humee y apenas burbujee — burbujitas en los bordes, no hervor rodante.",
            "<b>Bate vigorosamente.</b> La espuma superior es una firma del chocolate caliente puertorriqueño. Bate fuerte el último minuto de cocción para incorporar aire. Si tienes un molinillo, ruedalo entre tus palmas para la técnica traditional de espumado.",
            "<b>Usa chocolate real.</b> El cacao en polvo mezclado con agua o leche hace cocoa caliente, no chocolate caliente. Lo real usa chocolate derretido de verdad, lo que le da la riqueza y el cuerpo que definen la bebida.",
            "<b>Sirve de inmediato.</b> El chocolate caliente está mejor fresco y caliente. La espuma se disipa al enfriarse, y el chocolate puede espesar al reposar. Hazlo justo antes de beberlo.",
        ],
        "faqs": [
            {"q": "¿Qué chocolate debo usar para chocolate caliente?", "a": "La elección traditional son las tabletas de chocolate mexicano — Ibarra y Abuelita son las dos marcas más comunes. Vienen premezcladas con azúcar y canela y se disuelven bellamente en leche caliente. Las encuentras en Walmart, Target y cualquier supermercado latino. Si no las encuentras, usa 4 oz de buen chocolate oscuro (60-70% cacao) con 1/2 cdta extra de canela molida y una cucharada extra de azúcar."},
            {"q": "¿Puedo hacer chocolate caliente sin lácteos?", "a": "Sí — la leche de avena es el mejor sustituto sin lácteos porque es cremosa y de sabor neutro. Usa leche de avena estilo barista para mejores resultados. La de coco también funciona y añade una capa extra de riqueza, aunque aporta sabor a coco. La de almendras es más ligera, así que la bebida no quedará tan rica."},
            {"q": "¿El chocolate caliente debe ser espeso o ligero?", "a": "El chocolate caliente traditional es de lado espeso — más parecido a chocolate derretido que a cocoa ligera. Las tabletas de chocolate mexicano espesan naturalmente la leche al disolverse. Si lo prefieres más ligero, añade un chorrito más de leche. Si lo quieres aún más espeso, añade una onza extra de chocolate o una cucharada de maicena disuelta en leche fría."},
        ],
    },
    "chuletas": {
        "title": "Chuletas Kan Kan — Receta Puertorriqueña de Chuletas de Cerdo",
        "desc": "Aprende a hacer chuletas kan kan — las icónicas chuletas de cerdo puertorriqueñas dobles, crujientes y jugosas. Empanizadas y fritas a la perfección dorada.",
        "eyebrow": "Platos principales",
        "trust": ["30 minutos", "Fácil"],
        "serves": "Rinde 4 porciones:",
        "intro": "Las <b>chuletas kan kan</b> son las icónicas chuletas de cerdo puertorriqueñas de corte doble — crujientes, jugosas, empanizadas y fritas a la perfección dorada. Llevan el nombre del hueso que sobresale como un asa, y son el centro de atención de cualquier parrillada puertorriqueña seria. Mientras el pernil se hornea lento por horas, las chuletas kan kan entregan esa misma satisfacción de cerdo en menos de 30 minutos. El exterior desarrolla una costra dorada profunda gracias al empanizado, mientras el interior se mantiene jugoso y tierno. Servidas con arroz con gandules, tostones y un chorrito de salsa picante, esta es la comida reconfortante puertorriqueña en su punto máximo.",
        "whatis": [
            "Las chuletas kan kan son chuletas de cerdo gruesas con hueso — usualmente de corte doble para que el hueso sea largo y dramático — sazonadas con sazón, empanizadas en harina, huevo y pan rallado, luego fritas hasta un dorado profundo. El nombre 'kan kan' viene del hueso largo que sobresale, parecido a la pierna de una bailarina de cancán (según cuenta la historia).",
            "Son un básico de las parrilladas puertorriqueñas, servidas junto a tostones, maduros, arroz y habichuelas. A diferencia de las chuletas más delgadas que se secan rápido, el grosor del corte doble las mantiene jugosas durante la fritura. El sazón le da al empanizado ese tono naranja-dorado característico que te dice que estas son puertorriqueñas, no cualquier chuleta frita.",
        ],
        "first_h2_es": "¿Qué son las Chuletas Kan Kan?",
        "ingredients": [
            '<b><span class="ing-qty" data-base="4">4</span> chuletas de cerdo dobles con hueso</b> — de unas 1.5 pulgadas de grosor. Pídeselas a tu carnicero.',
            '<b><span class="ing-qty" data-base="2" data-unit="tablespoons">2 cucharadas</span> de sazón</b> — Sazón Goya con culantro y achiote funciona genial.',
            '<b><span class="ing-qty" data-base="1" data-unit="tablespoon">1 cucharada</span> de ajo en polvo</b> — no sal de ajo — la sal la controlas aparte.',
            '<b><span class="ing-qty" data-base="1" data-unit="teaspoon">1 cucharadita</span> de orégano seco</b> — orégano puertorriqueño si lo tienes.',
            '<b>Sal y pimienta negra</b> — al gusto.',
            '<b><span class="ing-qty" data-base="1" data-unit="cup">1 taza</span> de harina todo uso</b> — la primera capa del empanizado.',
            '<b><span class="ing-qty" data-base="3">3</span> huevos, batidos</b> — la pega que sostiene el pan rallado.',
            '<b><span class="ing-qty" data-base="1.5" data-unit="cups">1 1/2 tazas</span> de pan rallado</b> — regular o estilo italiano para extra sabor.',
            '<b>Aceite vegetal para freír</b> — unas 1/2 pulgada de profundidad en un sartén pesado.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay chuletas dobles?</b> Las chuletas regulares con hueso funcionan — solo reduce el tiempo de fritura a 3-4 minutos por lado y vigila el término.",
            "<b>¿No hay sazón?</b> Sustituye con 1 cucharada de paprika + 1 cucharadita de ajo en polvo + 1/2 cucharadita de cúrcuma para color y sabor similares.",
            "<b>¿Versión al horno?</b> Empaniza las chuletas, colócalas en rejilla sobre bandeja, rocía con aceite en spray y hornea a 400°F por 25-30 minutos, volteando a mitad de camino. No tan crujiente pero igual delicioso.",
        ],
        "steps": [
            "<b>Sazona las chuletas.</b> Seca las chuletas con toallas de papel. Sazona generosamente por ambos lados con sazón, ajo en polvo, orégano, sal y pimienta. Déjalas reposar a temperatura ambiente 10 minutos para que penetre el sazonado.",
            "<b>Arma la estación de empanizado.</b> Coloca harina en un plato hondo, huevos batidos en otro, y pan rallado en un tercero. Este es el clásico proceso de empanizado en tres pasos.",
            "<b>Empaniza las chuletas.</b> Pasa cada chuleta por la harina (sacude el exceso), sumérgela en el huevo (deja escurrir el exceso), luego presiónala firmemente en el pan rallado, cubriendo cada superficie. Presiona las migas — necesitan adherirse.",
            "<b>Calienta el aceite.</b> Vierte unas 1/2 pulgada de aceite vegetal en un sartén pesado (hierro fundido es ideal). Calienta a fuego medio-alto hasta llegar a 350°F — una miga de pan dejada caer debe chisporrotear de inmediato.",
            "<b>Fríe las chuletas.</b> Coloca las chuletas con cuidado, lejos de ti, en el aceite caliente. Fríe 4-5 minutos por lado hasta dorado profundo. La temperatura interna debe llegar a 145°F. Trabaja en tandas si es necesario — no satures el sartén.",
            "<b>Escurre y sirve.</b> Transfiere a una rejilla (no toallas de papel — hacen que la base quede pasable). Deja reposar 2 minutos. Sirve con arroz con gandules, tostones y un chorrito de limón.",
        ],
        "tips_h2": "Consejos para Chuletas Kan Kan Perfectas",
        "tips": [
            "<b>Seca las chuletas antes de sazonar.</b> La humedad es enemiga de la costra crujiente. Primero toallas de papel, luego sazona.",
            "<b>Presiona el pan rallado firmemente.</b> No lo pongas nomás — presióalo contra el huevo con tus manos para que adhiera durante la fritura.",
            "<b>No satures el sartén.</b> Fríe en tandas. La saturación baja la temperatura del aceite y crea empanizado pastoso.",
            "<b>Usa rejilla para escurrir.</b> Las toallas de papel atrapan vapor contra la base de la chuleta. La rejilla mantiene la costra crujiente por todos lados.",
            "<b>Deja reposar 2 minutos.</b> Los jugos se redistribuyen. Cortar muy temprano significa cerdo seco.",
        ],
        "faqs": [
            {"q": "¿Qué corte de cerdo usar?", "a": "Las chuletas dobles con hueso son el estándar de oro — de unas 1.5 pulgadas de grosor con el hueso largo adherido. Si no encuentras doble corte, las chuletas regulares con hueso funcionan bien. Evita las deshuesadas — se secan demasiado rápido en la fritura. Pide al carnicero que las corte gruesas si la tienda no las tiene pre-cortadas."},
            {"q": "¿Puedo hornearlas en vez de freírlas?", "a": "Sí. Precalienta el horno a 400°F. Empaniza las chuletas como indica la receta, colócalas en rejilla sobre bandeja, rocía las tapas con spray de aceite y hornea 25-30 minutos, volteando a mitad de camino. No serán tan crujientes como fritas, pero siguen muy buenas y con menos desorden. La rejilla es esencial — permite que circule el aire por debajo."},
            {"q": "¿Cómo consigo una costra extra crujiente?", "a": "Tres cosas importan: asegúrate de que el aceite esté a 350°F antes de meter las chuletas (frío = grasoso), presiona el pan rallado firmemente para que no se caiga, y no satures el sartén — cada chuleta necesita su espacio. El pan panko da un resultado aún más crocante que el pan rallado regular. Y siempre escurre en rejilla, nunca en toallas de papel."},
        ],
    },
    "empanadillas": {
        "title": "Empanadillas — Receta Puertorriqueña de Empanadas de Carne",
        "desc": "Aprende a hacer empanadillas, los queridos bolsillos de masa frita puertorriqueños rellenos de carne con sofrito, sazón y aceitunas.",
        "eyebrow": "Frituras",
        "trust": ["45 minutos", "Media"],
        "serves": "Rinde 12 empanadillas:",
        "intro": "Las empanadillas son la respuesta de Puerto Rico a la empanada — bolsillos de masa más grandes y suaves rellenos de carne sazonada. Todo boricua tiene recuerdos de comerlas en reuniones familiares y almuerzos escolares. Hay algo en la forma en que la masa frita crujiente cede ante ese relleno savory de carne molida, aceitunas y huevo duro que las hace imposibles de comer solo una. A diferencia de la empanada argentina, más delgada y crocante, la empanadilla puertorriqueña usa un disco más grueso y maleable que se infla al freírse, creando una costra almohadillada alrededor del relleno. Son la máxima fritura — portátiles, compartibles e infinitamente satisfactorias. Ya sea para una fiesta o una cena de semana, las empanadillas entregan ese consuelo boricua inconfundible en cada bocado.",
        "whatis": [
            "Las empanadillas son turnovers puertorriqueños fritos rellenos de carne molida sazonada. Se hacen con discos — rondas de masa para empanadas premade que encuentras en la sección congelada de la mayoría de supermercados. El relleno es una mezcla clásica tipo picadillo: carne molida cocinada con sofrito, sazón, salsa de tomate, aceitunas picadas y huevo duro en cubitos. La combinación de carne savory, aceitunas salobres y huevo cremoso es únicamente boricua. Tras rellenar y sellar, se fríen hasta quedar doradas e infladas. En Puerto Rico, encontrarás empanadillas en prácticamente cada fritura, cafeteria escolar y reunión familiar. Son comida reconfortante en su forma más pura — sin platos, sin pretensión, solo un bolsillo dorado de delicia que comes con las manos.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="1" data-unit="lb">1 libra</span> de carne molida</b> — la 80/20 regular funciona mejor para sabor. La magra puede saber seca dentro de la masa frita.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4</span> taza de sofrito</b> — casero o comprado. La base aromática del relleno.',
            '<b><span class="ing-qty" data-base="1" data-unit="packet">1</span> sobrecito de sazón con culantro y achiote</b> — le da al relleno ese color y profundidad característicos.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2</span> taza de salsa de tomate</b> — añade humedad y un toque de dulzor a la carne.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4</span> taza de aceitunas, picadas</b> — manzanilla con pimiento. El contraste salobre a la carne rica.',
            '<b><span class="ing-qty" data-base="1">1</span> huevo duro, picado</b> — una adición clásica que aporta cremosidad y textura.',
            '<b><span class="ing-qty" data-base="12" data-unit="discos">12</span> discos (tapas para empanadas)</b> — se encuentran congelados en el pasillo latino. Goya es la marca más común.',
            '<b>Aceite para freír</b> — vegetal o canola. Necesitas unas 2-3 pulgadas en la olla.',
            '<b>Sal al gusto</b>',
        ],
        "swaps_h3": None,
        "swaps": [],
        "steps": [
            "<b>Dora la carne.</b> Calienta un sartén grande a fuego medio-alto. Añade la carne molida y desmenúzala con una cuchara. Cocina hasta dorar completamente, unos 5-7 minutos. Escurre el exceso de grasa.",
            "<b>Construye el relleno.</b> Añade el sofrito, el sazón, la salsa de tomate, las aceitunas picadas y el huevo duro a la carne. Revuelve todo y cocina 5 minutos. La cocina debería oler increíble a estas alturas. Sazona con sal y prueba antes de retirar del fuego.",
            "<b>Enfría el relleno.</b> Transfiere el relleno a un plato o bol y deja enfriar completely. Esto es importante — el relleno tibio volverá los discos gomosos y difíciles de manejar. Puedes acelerarlo extendiéndolo plano en una bandeja.",
            "<b>Rellena y sella.</b> Coloca un disco sobre una superficie limpia. Pon unas 2 cucharadas de relleno ligeramente fuera del centro. Dobla la masa para crear forma de media luna. Presiona los bordes firmemente con un tenedor para sellar — asegúrate de que no haya aberturas o el relleno se escapará durante la fritura.",
            "<b>Fríe hasta dorar.</b> Calienta 2-3 pulgadas de aceite a 350°F en una olla profunda. Baja 2-3 empanadillas a la vez con cuidado — no satures. Fríe 3-4 minutos por lado hasta dorado profundo. Escurre en toallas de papel y sirve calientes.",
        ],
        "tips_h2": "Consejos para Empanadillas Perfectas",
        "tips": [
            "<b>Enfría el relleno completely.</b> Este es el error #1. El relleno tibio crea vapor dentro del disco, lo que provoca que explote en el aceite. Extiende el relleno en un plato y dale al menos 15 minutos.",
            "<b>Sella con tenedor.</b> Presiona las púas firmemente a lo largo de todo el borde. También puedes humedecer el borde con un poco de agua antes de sellar para asegurar contra fugas.",
            "<b>No sobre-rellenes.</b> 2 cucharadas es el punto ideal. Más que eso y el disco no cerrará bien, o el relleno se saldrá durante la fritura.",
            "<b>Vigila la temperatura del aceite.</b> Muy caliente y el exterior se quema antes de que la masa se cocine. Muy frío y las empanadillas absorben demasiado aceite y quedan grasosas. 350°F es la meta.",
        ],
        "faqs": [
            {"q": "¿Puedo hornear las empanadillas en lugar de freírlas?", "a": "Sí, aunque la textura será diferente. Precalienta el horno a 400°F, coloca las empanadillas en una bandeja forrada con pergamino, cepíllalas con huevo batido y hornea 15-18 minutos hasta dorar. Serán más hojaldradas y menos infladas que la versión frita — más parecidas a un turnover horneado. Igualmente deliciosas, solo que no es la experiencia tradicional de fritura."},
            {"q": "¿Qué discos debo usar?", "a": "Los discos Goya son el estándar — vienen en la sección congelada etiquetados 'discos para empanadillas'. Miden unas 5-6 pulgadas de diámetro, el tamaño correcto para un relleno generoso. Si no encuentras discos, puedes estirar masa de pastelón o masa de empanadas desde cero, pero los premade ahorran mucho tiempo y son muy indulgentes."},
            {"q": "¿Puedo congelar empanadillas?", "a": "Claro. Puedes congelarlas antes o después de freírlas. Para empanadillas crudas, colócalas en una bandeja en una sola capa, congélalas hasta solidificar, luego pásalas a bolsa de congelador. Duran hasta 3 meses. Fríelas directamente congeladas — añade 1-2 minutos al tiempo de cocción. Si congelas después de freír, recalienta en horno a 375°F unos 10 minutos para recuperar el crunch de la masa."},
        ],
    },
}
