# -*- coding: utf-8 -*-
"""ES translations batch 1/5: alcapurrias, arepas-de-coco, asopao, avena, bacalaitos."""

DATA = {
    "alcapurrias": {
        "title": "Alcapurrias — Receta Puertorriqueña de Frituras Rellenas",
        "desc": "Aprende a hacer alcapurrias, la comida callejera puertorriqueña por excelencia. Frituras de plátano verde y yautía rellenas de carne sazonada, fritas hasta dorar.",
        "eyebrow": "Frituras",
        "trust": ["1 hora", "Media"],
        "serves": "Para 8 alcapurrias:",
        "intro": "Si los bacalaítos son la fritura rápida y casual de Puerto Rico, las <b>alcapurrias</b> son la gran dama — el trabajo de amor que requiere rallar, mezclar, rellenar, dar forma y freír, pero que te premia con algo que ninguna otra fritura del Caribe puede igualar. Una alcapurria es una fritura con forma de torpedo hecha de una masa de plátano verde y yautía rallados, envuelta alrededor de un relleno sabroso de carne molida sazonada, y luego frita hasta que el exterior queda crujiente mientras el interior se mantiene tierno y almidonado. El resultado es una costra dorada y crocante que encierra carne jugosa con sazón — es la comida por la que son famosos los kioscos de Piñones. Las alcapurrias son la máxima comida callejera puertorriqueña y, aunque requieren más esfuerzo que otras frituras, la recompensa es extraordinaria.",
        "whatis": [
            "Las alcapurrias son la fritura rellena más icónica de Puerto Rico — una masa espesa de plátano verde y yautía rallados, rellena de picadillo (carne molida sazonada) y frita hasta dorar. La masa es lo que las hace únicas: a diferencia de un batido de harina o maíz, los tubérculos rallados crean una costra densa y almidonada que se dora bellamente en aceite caliente mientras permanece tierna por dentro. El relleno es el clásico picadillo puertorriqueño — carne molida cocinada con sofrito, sazón, salsa de tomate y aceitunas. Algunas familias añaden alcaparras, otras pasas para un toque dulce, y otras lo mantienen simple con lo básico.",
            "Encontrarás alcapurrias en cada <i>kiosko</i> de la isla, especialmente en la costa. Son la comida que comes de pie, con servilleta de papel en mano, mirando las olas. Son más grandes que los bacalaítos, más sustanciosas que las empanadillas y más complejas que cualquier otra cosa de la familia de las frituras. Hacerlas en casa es un proyecto de fin de semana — solo rallar toma tiempo — pero es una de esas recetas que te conecta directamente con la tradición callejera de la isla.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="2" data-unit="green">2</span> plátanos (verdes)</b> — firmes, con cáscara verde. Crean la base almidonada de la masa. NO uses plátanos maduros.',
            '<b><span class="ing-qty" data-base="1" data-unit="lb">1</span> libra de yautía</b> — también llamada malanga o dasheen. La variedad de carne blanca es la tradicional. Búscala en supermercados latinos o asiáticos.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4</span> taza de aceite vegetal</b> — mezclado en la masa para suavidad y para ayudar a que se fría parejo.',
            '<b><span class="ing-qty" data-base="1" data-unit="tablespoon">1</span> cucharada de sal</b> — para sazonar la masa. Prueba antes de añadir más — el relleno ya está salado.',
            '<b><span class="ing-qty" data-base="1" data-unit="lb">1</span> libra de carne molida</b> — la magra funciona mejor. El relleno debe estar jugoso pero no grasoso.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4</span> taza de sofrito</b> — la base de sabor del relleno de picadillo.',
            '<b><span class="ing-qty" data-base="1" data-unit="packet">1</span> sobrecito de sazón con culantro y achiote</b> — para color y ese sabor puertorriqueño inconfundible.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2</span> taza de salsa de tomate</b> — le da al relleno su carácter jugoso y rojizo.',
            '<b>Aceitunas manzanilla (opcional)</b> — unas cuantas aceitunas en el relleno añaden toques salados. Algunas familias usan alcaparras en su lugar.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay yautía?</b> La papa blanca es el sustituto almidonado más cercano — usa como 1 libra, pelada y rallada. La textura será un poco diferente pero funciona. Algunos usan una mezcla de plátano verde y papa.",
            "<b>¿Rallar es muy difícil?</b> Un procesador de alimentos con accesorio de rallado hace el trabajo rápido con los plátanos y la yautía. No los licúes — quieres un rallado fino, no una pasta.",
            "<b>¿No hay plátanos verdes?</b> Esto es difícil — los plátanos maduros no funcionan en absoluto (demasiado dulces y blandos). Si solo encuentras maduros, espera unos días. Los plátanos verdes están disponibles en la mayoría de los supermercados latinos.",
        ],
        "steps": [
            "<b>Haz la masa.</b> Pela y ralla finamente los plátanos verdes y la yautía. Escurre el exceso de humedad con las manos, luego mézclalos en un bol grande con el aceite y la sal. La masa debe mantenerse unida al presionarla — añade una cucharada de agua si está muy quebradiza.",
            "<b>Cocina el relleno.</b> En un sartén a fuego medio-alto, dora la carne molida. Añade el sofrito y cocina 2 minutos. Incorpora el sazón, la salsa de tomate y las aceitunas. Cocina a fuego lento 5 minutos hasta que esté jugoso pero no aguado. Deja enfriar un poco — el relleno caliente deshará la masa.",
            "<b>Forma las alcapurrias.</b> Toma como 1/2 taza de masa y aplánala en un óvalo sobre tu palma mojada. Coloca una cucharada generosa de relleno en el centro. Dobla la masa por encima y pellizca para sellar, dando forma de torpedo de unas 5 pulgadas. Moja tus manos según sea necesario para evitar que la masa se pegue.",
            "<b>Fríe hasta dorar.</b> Calienta aceite a 350°F en una olla profunda. Baja las alcapurrias al aceite con cuidado — no las dejes caer o la masa se agrietará. Fríe 5-7 minutos, girando ocasionalmente, hasta que el exterior esté dorado oscuro y crujiente por todos lados.",
            "<b>Escurre y sirve.</b> Retíralas a una rejilla o toallas de papel. Déjalas reposar 2-3 minutos (el interior está al rojo vivo). Sirve con kétchup, mayonesa o tu salsa picante favorita. Ese primer bocado — costra crujiente, masa tierna, carne sabrosa — es pura magia.",
        ],
        "tips_h2": "Consejos para Alcapurrias Perfectas",
        "tips": [
            "<b>Escurre la humedad.</b> Después de rallar los plátanos y la yautía, escúrrelos en una tela limpia o gasa. El exceso de humedad hace que la masa se deshaga en el aceite.",
            "<b>Moja tus manos.</b> Ten un bol de agua cerca mientras das forma. Las palmas húmedas evitan que la masa se pegue y te ayudan a crear alcapurrias suaves y sin grietas.",
            "<b>Deja enfriar el relleno.</b> El relleno caliente ablandará la masa e imposibilitará darle forma. Cocina el picadillo primero, luego haz la masa mientras se enfría.",
            "<b>Fríe a la temperatura correcta.</b> Muy frío y absorben aceite y quedan grasosas. Muy caliente y el exterior se quema antes de que el interior se cocine. 350°F es la meta — usa un termómetro.",
        ],
        "faqs": [
            {"q": "¿Qué es exactamente la yautía?", "a": "La yautía es un tubérculo almidonado también conocido como taro, malanga o dasheen dependiendo de dónde seas. La variedad de carne blanca se usa en la cocina puertorriqueña. Tiene un sabor suave, ligeramente nuez, y una textura densa similar a la papa cuando está cruda. Encuéntrala en supermercados latinos o asiáticos — suele venderse como un tubérculo marrón de piel áspera. Si no la encuentras, la papa blanca es el sustituto más cercano."},
            {"q": "¿Puedo hornearlas en lugar de freírlas?", "a": "Puedes intentarlo, pero no es lo mismo. Las alcapurrias horneadas no desarrollarán la costra crujiente característica que da la fritura. Si es necesario, hornéalas a 400°F en una bandeja engrasada por 25-30 minutos, volteándolas a mitad de camino. La textura será más de empanada horneada que de fritura. Algunas personas las fríen en air fryer a 375°F por 12-15 minutos con resultados decentes — medianamente crujientes por fuera pero sin la magia de la fritura profunda."},
            {"q": "¿Puedo congelar alcapurrias?", "a": "Sí — este es el mejor truco de meal prep para alcapurrias. Formadas completamente, congélalas en una bandeja en una sola capa. Una vez sólidas, pásalas a una bolsa de congelador. Se mantienen 2-3 meses. Para cocinarlas congeladas, fríelas directamente a 350°F por 7-9 minutos (un par de minutos más que frescas). No las descongeles antes — la masa se mojará demasiado y se deshará."},
        ],
    },
    "arepas-de-coco": {
        "title": "Arepas de Coco — Receta Puertorriqueña de Frituras de Coco",
        "desc": "Aprende a hacer arepas de coco, frituras puertorriqueñas de harina de coco. Crujientes por fuera, esponjosas por dentro y naturalmente sin gluten. Listas en 20 minutos.",
        "eyebrow": "Frituras",
        "trust": ["20 minutos", "Fácil"],
        "serves": "Para 4 porciones:",
        "intro": "Las <b>arepas de coco</b> son frituras de harina de coco — una fritura naturalmente sin gluten y absolutamente adictiva. Son crujientes por fuera, esponjosas por dentro, y tienen ese dulzor sutil de coco que hace imposible dejar de comerlas. Las encontrarás en los kioscos de playa por todo Puerto Rico, servidas en bolsitas de papel junto a bacalaítos y surullitos. Son el tipo de snack que desaparece del plato antes de que alguien recuerde guardar una para la persona que aún está friendo. Hechas con harina de coco, coco rallado y leche de coco, son una celebración del coco en todas sus formas — y están listas en 20 minutos planos. Sin equipo especial, sin técnica complicada, solo ingredientes simples fritos a la perfección dorada.",
        "whatis": [
            "Las arepas de coco son frituras de harina de coco que forman parte querida de la tradición de frituras de Puerto Rico. Mientras que 'arepa' en muchos países latinoamericanos se refiere a una torta de maíz, en Puerto Rico la versión de coco es algo distinto — pequeñas frituras redondas hechas con harina de coco, coco rallado, huevos y leche de coco, fritas hasta quedar doradas y crujientes. El resultado es un snack naturalmente sin gluten, ligeramente dulce e increíblemente satisfactorio.",
            "Encontrarás arepas de coco en kioscos de carretera, chiringuitos de playa y reuniones familiares por toda la isla. Son parte de la familia de las frituras — la tradición puertorriqueña de snacks fritos que incluye tostones, bacalaítos, surullitos y alcapurrias. Pero las arepas de coco destacan por su simplicidad y su sabor pronunciado a coco. La mezcla se prepara en un bol, la fritura toma minutos, y el resultado sabe a mucho más esfuerzo del que tomó. Son perfectas solas, mojadas en una mayonesa con ajo, o junto a una bebida fría en una tarde calurosa.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="1" data-unit="cup">1 taza</span> de harina de coco</b> — no harina de almendras ni harina regular. La harina de coco es esencial para la textura y el sabor.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2 taza</span> de coco rallado</b> — endulzado o sin endulzar, cualquiera funciona. El sin endulzar da un sabor a coco más sutil.',
            '<b><span class="ing-qty" data-base="2" data-unit="eggs">2 huevos</span></b> — el aglutinante que mantiene unida la mezcla.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4 taza</span> de leche de coco</b> — la de lata es mejor por su riqueza. La de cartón funciona pero es más ligera.',
            '<b><span class="ing-qty" data-base="2" data-unit="tablespoons">2 cucharadas</span> de azúcar</b> — justo lo necesario para resaltar el dulzor natural del coco sin volverlas postre.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="teaspoon">1/2 cucharadita</span> de polvo de hornear</b> — para un interior más ligero y esponjoso.',
            '<b>Una pizca de sal</b> — balancea el dulzor y realza el sabor a coco.',
            '<b>Aceite para freír</b> — aceite vegetal o canola con alto punto de humo.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay harina de coco?</b> No puedes sustituirla por harina regular aquí — la harina de coco es todo el punto. La harina de coco está disponible en la mayoría de supermercados en el pasillo de repostería, o en línea.",
            "<b>¿No hay leche de coco en lata?</b> Usa la bebida de coco de cartón en caso apremiante. Las frituras serán un poco menos ricas pero seguirán buenas.",
            "<b>¿Las quieres saladas?</b> Omite el azúcar y añade 2 cucharadas de cebollín finamente picado o una pizca de ajo en polvo.",
        ],
        "steps": [
            "<b>Mezcla los ingredientes secos.</b> En un bol mediano, combina la harina de coco, el coco rallado, el polvo de hornear y la sal. Revuelve para distribuir todo uniformemente.",
            "<b>Añade los ingredientes húmedos.</b> Rompe los huevos, vierte la leche de coco y añade el azúcar. Mezcla hasta formar una masa espesa. La harina de coco absorbe mucho líquido, así que la mezcla será más espessa de lo que esperas — eso es normal.",
            "<b>Calienta el aceite.</b> Vierte como una pulgada de aceite en un sartén pesado y calienta a fuego medio hasta unos 350°F. Si no tienes termómetro, deja caer un pedacito de masa — debe chisporrotear de inmediato y flotar.",
            "<b>Fríe las frituras.</b> Deja caer cucharadas de masa en el aceite caliente — no satures el sartén. Fríe 2-3 minutos por lado hasta dorado oscuro. La harina de coco se dora más rápido que la regular, así que vigílalas de cerca.",
            "<b>Escurre y sirve.</b> Transfiere las frituras a un plato forrado con toallas de papel para escurrir el exceso de aceite. Sirve calientes — están mejores recién salida del aceite cuando el exterior aún está crujiente.",
        ],
        "tips_h2": "Consejos para Arepas de Coco Perfectas",
        "tips": [
            "<b>No te saltes el reposo.</b> Después de mezclar, deja reposar la masa 2-3 minutos. La harina de coco sigue absorbiendo líquido mientras reposa, lo que le da la consistencia correcta para freír.",
            "<b>Vigila la temperatura del aceite.</b> Muy caliente y el exterior se quema antes de que el interior se cocine. Muy frío y las frituras absorben demasiado aceite y quedan grasosas. Fuego medio con meta de 350°F es el punto ideal.",
            "<b>Usa una cuchara porcionadora.</b> Para frituras uniformes, usa una cuchara porcionadora pequeña o dos cucharas para dejar caer la masa. Así todas se cocinan al mismo ritmo.",
            "<b>Sirve de inmediato.</b> Las arepas de coco están mejores a los minutos de freírse. El exterior de harina de coco se mantiene crujiente un rato, pero pierden el crunch al enfriarse. Si debes guardarlas, mantenlas calientes en un horno a 200°F.",
        ],
        "faqs": [
            {"q": "¿Las arepas de coco son libres de gluten?", "a": "Sí — las arepas de coco son naturalmente libres de gluten. La mezcla se hace completamente con harina de coco, coco rallado, huevos y leche de coco. No participa harina de trigo. Solo asegúrate de que tu polvo de hornear sea libre de gluten (la mayoría de marcas lo son, pero revisa la etiqueta)."},
            {"q": "¿Puedo usar harina regular en lugar de harina de coco?", "a": "Puedes, pero entonces ya no son arepas de coco — se vuelven frituras regulares. La harina de coco absorbe significativamente más líquido que la de trigo y tiene un sabor y textura distintivos. Si la sustituyes, tendrías que ajustar drásticamente el ratio de líquidos, y se perdería el sabor a coco. Si quieres frituras de coco, usa harina de coco."},
            {"q": "¿Las arepas de coco deben ser dulces o saladas?", "a": "Tradicionalmente son ligeramente dulces — justo suficiente azúcar para complementar el dulzor natural del coco sin convertirlas en postre. Las 2 cucharadas de azúcar de esta receta dan con ese balance. Algunas familias las hacen completely sin azúcar y las sirven con una salsa salada para mojar. Ambas versiones son deliciosas — es cuestión de preferencia personal."},
        ],
    },
    "asopao": {
        "title": "Asopao de Pollo — Receta Puertorriqueña de Guiso de Pollo y Arroz",
        "desc": "Aprende a hacer asopao de pollo, el querido guiso puertorriqueño de pollo y arroz. Más espeso que sopa, más jugoso que arroz con pollo — pura comida de alma.",
        "eyebrow": "Platos principales",
        "trust": ["1 hora", "Media"],
        "serves": "Para 6 porciones:",
        "intro": "El <b>asopao</b> es el híbrido que Puerto Rico hace mejor que nadie — más espeso que sopa, más jugoso que el arroz con pollo, y cargado de pollo, aceitunas y alcaparras. Se sitúa justo en el medio del espectro de la comida reconfortante puertorriqueña: un guiso suficientemente jugoso para comer con cuchara pero suficientemente contundente para llenarte por completo. El arroz se cocina directamente en el caldo, absorbiendo el líquido de tomate y soltando almidón que espesa todo hasta una consistencia brillante de guiso. Añade aceitunas saladas y alcaparras saladas, y tienes un plato que camina entre el consuelo y la celebración. El asopao es lo que haces cuando el arroz con pollo se siente muy seco y el sancocho muy ambicioso. Es la respuesta de una sola olla para una cena de semana que sabe a que tomó todo el día.",
        "whatis": [
            "El asopao es el querido guiso puertorriqueño de pollo y arroz — un plato que existe en el espacio entre la sopa y el arroz. La palabra viene de 'asopar', que significa comer sopa, pero el asopao es mucho más sustancioso que cualquier caldo con fideos. Es arroz cocinado en un caldo a base de tomate con pollo, aceitunas, alcaparras y sofrito, cocido a fuego lento destapado para que el arroz suelte su almidón y espese el líquido hasta una consistencia rica de guiso. El resultado se come con cuchara pero satisface como una cena de plato completo.",
            "Cada familia puertorriqueña hace el asopao un poco diferente. Algunos añaden guisantes, otros jamón en cubitos, otros mariscos en lugar del pollo o además de él. Pero la identidad central siempre es la misma: arroz, pollo, caldo de tomate, aceitunas y alcaparras. Es el plato que tiende el puente entre la cocina de todos los días y las ocasiones especiales — lo bastante fácil para un martes, lo bastante impresionante para un domingo. En Puerto Rico, el asopao es lo que le llevas a alguien que está enfermo, lo que cocinas cuando quieres impresionar sin complicarte, y lo que se te antoja cuando nada más sirve.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="2" data-unit="lbs">2 libras</span> de muslos de pollo</b> — con hueso y piel para el mejor sabor. Deshuesados funcionan también, pero el hueso añade profundidad al caldo.',
            '<b><span class="ing-qty" data-base="1.5" data-unit="cups">1.5 tazas</span> de arroz</b> — arroz blanco de grano largo. No uses instantáneo — se volverá papilla antes de que los sabores se desarrollen.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4 taza</span> de sofrito</b> — la base aromática. Casero es mejor, pero el Goya congelado funciona en apuros.',
            '<b><span class="ing-qty" data-base="1" data-unit="packet">1 sobrecito</span> de sazón</b> — sazón con culantro y achiote para color y ese tono naranja característico.',
            '<b><span class="ing-qty" data-base="1" data-unit="cup">1 taza</span> de salsa de tomate</b> — le da al caldo su base y cuerpo de tomate.',
            '<b><span class="ing-qty" data-base="6" data-unit="cups">6 tazas</span> de caldo de pollo</b> — bajo en sodio para controlar el nivel de sal.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2 taza</span> de aceitunas manzanilla</b> — los toques salados que cortan la riqueza del guiso.',
            '<b><span class="ing-qty" data-base="2" data-unit="tablespoons">2 cucharadas</span> de alcaparras</b> — saladas, ácidas y esenciales. No las omitas.',
            '<b><span class="ing-qty" data-base="2" data-unit="tablespoons">2 cucharadas</span> de aceite</b> — vegetal u oliva para dorar el pollo.',
            '<b>Sal y pimienta al gusto</b>',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay sazón?</b> Mezcla 1 cdta de cúrcuma + 1/2 cdta de ajo en polvo + 1/4 cdta de comino. No será exactamente igual, pero te da el color y el sabor base.",
            "<b>¿No hay alcaparras?</b> Usa una pequeña cantidad de aceitunas verdes picadas como sustituto. Lo importante es esa calidad salada y salobre.",
            "<b>¿Quieres asopao de mariscos?</b> Cambia el pollo por camarones y añádelos en los últimos 5 minutos de cocción. El asopao de camarones es una variación querida.",
        ],
        "steps": [
            "<b>Dora el pollo.</b> Sazona los muslos con sal y pimienta. Calienta aceite en una olla grande y pesada a fuego medio-alto. Dora el pollo por ambos lados — unos 4 minutos por lado. Retira y reserva.",
            "<b>Sofríe el sofrito.</b> En la misma olla con la grasa del pollo, añade el sofrito y cocina 2-3 minutos hasta que esté fragante. Raspa los bits dorados del fondo — eso es puro sabor.",
            "<b>Añade sazón y salsa de tomate.</b> Incorpora el sobrecito de sazón y la salsa de tomate. Cocina 2 minutos, revolviendo para integrar. El achiote del sazón pintará todo de un hermoso naranja-rojo.",
            "<b>Tuesta el arroz.</b> Añade el arroz y revuelve 1 minuto para cubrir cada grano con la mezcla de sofrito-tomate. Este tostado ayuda al arroz a mantener su forma durante el largo hervor lento.",
            "<b>Añade caldo, pollo, aceitunas y alcaparras.</b> Vierte el caldo de pollo, acomoda los muslos dorados de vuelta, y añade las aceitunas y alcaparras. Lleva a un hervor fuerte.",
            "<b>Cocina destapado 30 minutos.</b> Baja el fuego a medio-bajo y cocina sin tapa, revolviendo ocasionalmente para evitar que se pegue. El arroz soltará almidón y espesará el caldo hasta consistencia de guiso. Está listo cuando el arroz está tierno y la consistencia es espesa pero aún servible con cuchara.",
        ],
        "tips_h2": "Consejos para un Asopao Perfecto",
        "tips": [
            "<b>Cocina destapado.</b> La tapa se queda fuera durante los 30 minutos completos. Esto permite que el arroz suelte almidón y espese el caldo naturalmente. Taparlo haría el arroz suelto en vez de guisado.",
            "<b>Revuelve ocasionalmente.</b> A diferencia del arroz con pollo donde no tocas el arroz, el asopao necesita revueltas ocasionales. El almidón que se asienta en el fondo puede pegarse y quemarse si lo ignoras por completo.",
            "<b>Usa muslos de pollo.</b> La pechuga se seca durante el largo hervor. Los muslos se mantienen jugosos y tiernos, y la carne oscura añade riqueza al caldo.",
            "<b>No sobre-cocines el arroz.</b> El asopao debe ser espeso pero el arroz debe tener textura. Empieza a chequear a los 25 minutos — el arroz pasado convierte el guiso en papilla.",
        ],
        "faqs": [
            {"q": "¿En qué se diferencia el asopao del arroz con pollo?", "a": "La diferencia clave es el ratio de líquido y el método de cocción. El arroz con pollo se cocina tapado con menos líquido, produciendo granos de arroz sueltos y esponjosos. El asopao usa más líquido y se cocina destapado, así que el arroz suelta almidón y espesa el caldo hasta consistencia de guiso. Piensa en el asopao como el primo más jugoso y reconfortante del arroz con pollo."},
            {"q": "¿Qué tipo de arroz funciona mejor para asopao?", "a": "El arroz blanco de grano largo es el estándar. Mantiene su forma durante el largo hervor mientras suelta suficiente almidón para espesar el caldo. El jazmín también funciona. Evita el arroz instantáneo — se deshace muy rápido y vuelve el guiso gomoso. El grano corto o arborio lo harían demasiado espeso y almidonado."},
            {"q": "¿Puedo añadir camarones o mariscos al asopao?", "a": "El asopao de camarones es una variación puertorriqueña querida. Añade 1 libra de camarones grandes pelados durante los últimos 5 minutos de cocción para que no se sobre-cocinen. También puedes añadir carne de cangrejo o trozos de pescado blanco firme. Algunas familias hacen una versión mixta con pollo y camarones — la combinación de tierra y mar es increíble."},
        ],
    },
    "avena": {
        "title": "Avena — Receta Puertorriqueña de Bebida de Avena",
        "desc": "Aprende a hacer avena, la cremosa bebida puertorriqueña de avena. Caliente o fría, con canela y lista en 10 minutos.",
        "eyebrow": "Bebidas",
        "trust": ["10 minutos", "Fácil"],
        "serves": "Rinde 4 porciones:",
        "intro": "La <b>avena</b> es la bebida puertorriqueña de avena — cremosa, con canela, y servida caliente o fría. Es el smoothie de desayuno antes de que existieran los smoothies, un básico matutino en toda la isla. Mucho antes de que los batidos de proteína y los lattes de leche de avena se pusieran de moda, los boricuas ya licuaban avena con agua, azúcar y canela en una bebida que podía alimentar toda una mañana. Encontrarás avena en termos en las mesas de desayuno, en vasos plásticos de vendedores ambulantes, y en cafeterías junto al café con leche. Es reconfortante, llenadora y cuesta casi nada hacerla. Esta es la bebida que tu abuela hacía cuando quería que todos salieran por la puerta con algo cálido y nutritivo.",
        "whatis": [
            "La avena es una bebida tradicional puertorriqueña de avena hecha de copos de avena licuados, agua, azúcar y canela. A diferencia de la avena americana, que se come con cuchara, la avena es una bebida suave y vertible — piensa en ella como el smoothie original de la isla. La avena se licúa hasta quedar sedosa, se cuela para quitar cualquier aspereza, y luego se cocina a fuego lento con agua endulzada hasta que la bebida espesa lo justo para cubrir el dorso de una cuchara.",
            "Se sirve tanto caliente por la mañana como fría como refresco de la tarde. Algunas familias añaden un chorrito de leche, otras se quedan con la base tradicional de agua. La belleza de la avena es su simplicidad — cuatro o cinco ingredientes, una licuadora, una olla, y diez minutos. Eso es todo. Sin equipo fancy, sin ingredientes exóticos, solo una bebida que ha nutrido a familias puertorriqueñas por generaciones.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="1" data-unit="cup">1 taza</span> de avena en copos</b> — la avena old-fashioned funciona mejor. La instantánea se disuelve demasiado y pierde cuerpo.',
            '<b><span class="ing-qty" data-base="4" data-unit="cups">4 tazas</span> de agua</b> — divididas en 2 tazas para licuar y 2 para la olla.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2 taza</span> de azúcar</b> — ajusta al gusto. Algunas familias usan menos; otras un poco más.',
            '<b><span class="ing-qty" data-base="1" data-unit="teaspoon">1 cucharadita</span> de extracto de vainilla</b> — añade calidez y profundidad más allá de la canela.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="teaspoon">1/2 cucharadita</span> de canela molida</b> — la especia insignia. Usa más para espolvorear por encima.',
            '<b>Una pizca de sal</b> — ilumina todos los sabores.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay avena en copos?</b> La instantánea funciona pero produce una bebida más ligera. La cortada en acero da una textura más granulada — no recomendada a menos que cues muy bien.",
            "<b>¿La quieres más cremosa?</b> Sustituye 1 taza del agua por leche entera o leche de coco para una versión más rica.",
            "<b>¿Menos azúcar?</b> Usa 1/4 taza de azúcar o cambia por miel o leche condensada. Ajusta a tu preferencia.",
        ],
        "steps": [
            "<b>Licúa la avena.</b> Añade los copos de avena y 2 tazas de agua a la licuadora. Licúa a alta velocidad hasta que la mezcla esté completamente suave y cremosa — unos 60 segundos. No deben quedar pedazos visibles de avena.",
            "<b>Calienta el agua endulzada.</b> En una olla mediana, combina las 2 tazas restantes de agua, el azúcar y la canela. Lleva a un hervor suave a fuego medio, revolviendo hasta disolver el azúcar.",
            "<b>Cuela y combina.</b> Vierte la mezcla de avena licuada a través de un colador de malla fina hacia el agua caliente. Presiona con una cuchara para extraer todo el líquido. Descarta los sólidos.",
            "<b>Añade vainilla y sal.</b> Incorpora el extracto de vainilla y la pizca de sal. Estos dos últimos ingredientes marcan más diferencia de lo que esperarías.",
            "<b>Cocina 3 minutos.</b> Cocina a fuego medio-bajo por 3 minutos, revolviendo constantemente para evitar que se pegue. La avena espesará ligeramente — debe cubrir el dorso de una cuchara pero aún verterse fácilmente.",
            "<b>Sirve.</b> Vierte en tazas para una bebida cálida matutina, o refrigera 2 horas y sirve fría. Espolvorea con canela extra si quieres.",
        ],
        "tips_h2": "Consejos para una Avena Perfecta",
        "tips": [
            "<b>Licúa bien.</b> Cuanto más suave se licúe la avena, más cremosa será tu avena. Licúa un minuto completo — no te apures en este paso.",
            "<b>Cuela a fondo.</b> Usa un colador de malla fina o gasa. La avena sin colar tiene una textura arenosa que a la mayoría no le gusta.",
            "<b>Revuelve mientras hierves.</b> Las mezclas de avena aman pegarse y aglomerarse. Revolver constantemente esos últimos 3 minutos marca la diferencia entre sedosa y grumosa.",
            "<b>Sírvela a tu manera.</b> La avena caliente es una bebida reconfortante matutina. La avena fría es un refresco vespertino. Ambas son igual de auténticas — no hay forma incorrecta de tomarla.",
        ],
        "faqs": [
            {"q": "¿Puedo usar avena cortada en acero?", "a": "Puedes, pero no se licúa tan suave y producirá una textura más arenosa. Los copos son el estándar porque se deshacen fácilmente en la licuadora y crean esa consistencia sedosa. Si solo tienes avena cortada, licúala más tiempo y cuélala con gasa en vez de colador regular."},
            {"q": "¿Puedo hacer avena con anticipación?", "a": "Sí — la avena se conserva bien refrigerada hasta 4 días. Espesará al reposar, así que añade un chorrito de agua al recalentar para devolverle la consistencia. A algunas personas de hecho les gusta fría directo de la nevera como desayuno rápido."},
            {"q": "¿La avena es libre de lácteos?", "a": "La receta traditional es completamente libre de lácteos — solo avena, agua, azúcar y especias. No se requiere leche. Si quieres una versión más cremosa, puedes añadir leche o leche de coco, pero la avena clásica es naturalmente libre de lácteos y vegana."},
        ],
    },
    "bacalaitos": {
        "title": "Bacalaítos — Receta Puertorriqueña de Frituras de Bacalao",
        "desc": "Aprende a hacer bacalaítos, crujientes frituras puertorriqueñas de bacalao. Receta clásica con bacalao salado, ajo y perejil — perfectas para días de playa y fiestas.",
        "eyebrow": "Frituras",
        "trust": ["25 minutos", "Fácil"],
        "serves": "Para 4 porciones:",
        "intro": "Todo puertorriqueño tiene un recuerdo de <b>bacalaítos</b>. Quizás fue en un kiosco de la playa en Piñones, entregado a través de una servilleta tan caliente que te quemaba los dedos. Quizás fue en una fritura de carretera donde una abuela estaba detrás de una olla enorme de aceite burbujeante, volteándolos con un tenedor. O quizás fue en una fiesta familiar, donde un bol gigante de estas frituras crujientes y saladas de bacalao desapareció en minutos. Los bacalaítos son la <i>fritura</i> puertorriqueña quintessential — un batido simple de harina cargado de bacalao salado desmenuzado, ajo y perejil, frito hasta quedar dorado y crocante por fuera, tierno por dentro. No necesitan nada más que un chorrito de limón y una bebida fría. El nombre viene del <i>bacalao</i>, un ingrediente que llegó al Caribe desde el comercio pesquero del Atlántico Norte y se volvió parte permanente de las cocinas puertorriqueñas.",
        "whatis": [
            "Los bacalaítos son frituras planas y crujientes de bacalao hechas de un batido simple de harina, agua, polvo de hornear y bacalao salado desmenuzado sazonado con ajo y perejil. A diferencia de las alcapurrias (que usan una masa de plátano verde y yautía rallados), los bacalaítos son a base de harina — lo que los hace más rápidos, más simples y posiblemente la fritura puertorriqueña más accesible para hacer en casa. El batido es lo bastante líquido para extenderse un poco al tocar el aceite caliente, creando esos bordes irregulares y calados que quedan extra crujientes. El interior permanece tierno con hilos visibles de bacalao recorriéndolo. Se sirven como snack, aperitivo, u honestamente solo porque es martes y quieres algo rico.",
            "Encontrarás bacalaítos en cada <i>fritura</i> de la isla — esos puestos de carretera y kioscos de playa especializados en freír todo. A menudo se sirven junto a tostones, alcapurrias y empanadillas, pero los bacalaítos brillan por sí solos como estrellas de cualquier bandeja de frituras. El bacalao salado les da una calidad savory, casi umami, que las frituras de harina regulares no pueden igualar.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="1" data-unit="cup">1 taza</span> de bacalao salado</b> — remojado toda la noche en agua fría, escurrido y desmenuzado. Encuéntralo salado (no ahumado) en supermercados latinos o portugueses.',
            '<b><span class="ing-qty" data-base="1" data-unit="cup">1 taza</span> de harina todo uso</b> — la harina regular crea el batido fino y crujiente. No uses leudante.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="cup">1/2 taza</span> de agua</b> — añade gradualmente hasta lograr un batido espeso pero vertible, como consistencia de panqueques.',
            '<b><span class="ing-qty" data-base="2" data-unit="cloves">2 dientes</span> de ajo, picados</b> — el ajo fresco no es negociable aquí. El sabor es central en la fritura.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4 taza</span> de perejil, picado</b> — añade color y una nota herbal fresca que corta la salinidad.',
            '<b><span class="ing-qty" data-base="1" data-unit="teaspoon">1 cucharadita</span> de polvo de hornear</b> — justo para dar un poco de levitación sin volverlos esponjosos.',
            '<b>Aceite para freír</b> — vegetal o canola con alto punto de humo. Necesitas unas 2 pulgadas en el sartén.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay bacalao salado?</b> Puedes encontrar bacalao en la mayoría de supermercados latinos, portugueses o incluso escandinavos. En apuros, el bacalao en lata (no ahumado) funciona, aunque la textura es más blanda.",
            "<b>¿No hay perejil?</b> El cilantro añade una frescura diferente pero complementaria. En emergencia real, una cucharadita de perejil seco funciona — pero fresco siempre es mejor.",
            "<b>¿No hay freidora?</b> Un sartén de hierro pesado con 2 pulgadas de aceite funciona perfecto. Usa termómetro para mantener 350°F.",
        ],
        "steps": [
            "<b>Prepara el bacalao.</b> Escurre el bacalao remojado y desmenúzalo finamente con los dedos. Quita cualquier piel o espina que encuentres. Los hilos deben ser finos y fibrosos — esto es lo que da a los bacalaítos su textura característica.",
            "<b>Haz el batido.</b> En un bol grande, bate la harina y el polvo de hornear. Añade agua gradualmente, revolviendo hasta tener un batido espeso pero vertible — piensa en masa de panqueques. Debe gotear lentamente de la cuchara, no verterse como agua.",
            "<b>Incorpora el sabor.</b> Añade el bacalao desmenuzado, el ajo picado y el perejil al batido. Integra suavemente hasta distribuir parejo. Prueba un poquito del batido crudo — el bacalao es salado, así que probablemente no necesites mucha sal adicional.",
            "<b>Fríelos.</b> Calienta aceite a 350°F en un sartén profundo. Deja caer cucharadas de batido en el aceite — unas 2 cucharadas cada uno — y aplánalos ligeramente con el dorso de la cuchara. No satures; trabaja en tandas de 4-5.",
            "<b>Voltea y termina.</b> Fríe 2-3 minutos por lado hasta dorado profundo con bordes crujientes. Los bordes calados e irregulares son la mejor parte — quedan crujientes que se quiebran. Escurre en toallas de papel y sirve de inmediato con gajos de limón.",
        ],
        "tips_h2": "Consejos para Bacalaítos Perfectos",
        "tips": [
            "<b>Remoja el bacalao toda la noche.</b> Este es el paso más importante. Cubre el bacalao salado con agua fría y refrigera 12-24 horas, cambiando el agua 2-3 veces. Sáltate esto y tus frituras serán intolerablemente saladas.",
            "<b>Clava el batido.</b> Muy espeso y las frituras quedan masa por dentro. Muy líquido y se extienden en crujientes sin forma. Apunta a batido espeso de panqueque — debe gotear lento de la cuchara.",
            "<b>La temperatura del aceite importa.</b> Si el aceite está muy frío, las frituras absorben grasa y quedan pasables. Si está muy caliente, el exterior se quema antes de que el interior cocine. 350°F es el punto ideal — usa termómetro.",
            "<b>Sirve de inmediato.</b> Los bacalaítos están mejores a los minutos de freírse. Si debes guardarlos, mantenlos calientes en rejilla dentro de un horno a 200°F. Perderán el crunch en unos 15 minutos.",
        ],
        "faqs": [
            {"q": "¿Cómo desalo el bacalao correctamente?", "a": "Coloca el bacalao salado en un bol grande y cúbrelo con agua fría. Refrigera 12-24 horas, cambiando el agua 2-3 veces. Cuantas más veces cambies el agua, menos salado quedará el producto final. Tras el remojo, prueba un pedacito — debe saber moderadamente salado, como pescado bien sazonado. Si aún es agresivamente salado, remoja 6-12 horas más."},
            {"q": "¿Puedo usar bacalao fresco en vez de salado?", "a": "Puedes, pero no será lo mismo. El bacalao fresco tiene una textura y sabor muy diferentes — mucho más suave y húmedo. Si lo sustituyes, seca muy bien el pescado y añade como 1/2 cucharadita de sal al batido para compensar. Las frituras estarán buenas, pero el golpe salado distintivo de los bacalaítos tradicionales viene del bacalao salado. Vale la pena buscarlo."},
            {"q": "¿Qué consistencia debe tener el batido?", "a": "Piensa en batido espeso de panqueques — debe gotear de la cuchara en una cinta gruesa, no verterse como agua. Cuando dejas caer una cucharada en el aceite, debe mantener su forma y extenderse apenas. Si está muy espeso, añade agua una cucharadita a la vez. Si está muy líquido, añade harina una cucharada a la vez. El batido debe cubrir el dorso de una cuchara sin escurrirse de inmediato."},
        ],
    },
}
