# -*- coding: utf-8 -*-
"""ES translations batch 5/5: sopa-de-fideo, surullitos (tostones handled separately)."""

DATA = {
    "sopa-de-fideo": {
        "title": "Sopa de Fideo — Receta Puertorriqueña de Sopa de Fideos",
        "desc": "Aprende a hacer sopa de fideo, la comida reconfortante puertorriqueña con fideos tostados en caldo de tomate rico. Rápida, fácil y lista en 25 minutos.",
        "eyebrow": "Acompañantes y Arroz",
        "trust": ["25 minutos", "Fácil"],
        "serves": "Para 4 porciones:",
        "intro": "La <b>sopa de fideo</b> es comida reconfortante puertorriqueña en un bol — fideos tostados nadando en un caldo de tomate rico y con comino. Es el plato que hacía toda abuela cuando el clima se enfriaba o alguien necesitaba un ánimo. La magia empieza con los fideos: fideos delgados tostados en una sartén seca hasta dorarse, lo que les da una profundidad a nuez que los fideos hervidos regulares nunca pueden igualar. Luego hierven a fuego lento en un caldo simple de tomate construido sobre sofrito — la base aromática que hace que todo sepa a hogar. No requiere carne, ni técnica complicada, ni ingrediente que no encuentres en un supermercado regular. Es sopa en su forma más honesta: un puñado de básicos de despensa transformados en algo que sabe a que la abuela de alguien pasó todo el día en ello. ¿Y lo mejor? Está lista en 25 minutos.",
        "whatis": [
            "La sopa de fideo — literalmente 'fideos' — es un básico en cocinas latinoamericanas, pero la versión puertorriqueña tiene su propia identidad. Se construye sobre dos cosas: fideos tostados y un caldo de sofrito-tomate. Los fideos suelen ser fideos cortos y delgados tipo vermicelli que vienen en bolsa en el pasillo latino de la mayoría de supermercados. Tostarlos en un sartén seco antes de añadir líquido es el paso innegociable — transforma pasta sin sabor en algo con carácter real, dando a cada hebra una tostada a nuez que impregna todo el bol.",
            "El caldo es simple pero por capas: sofrito para profundidad, salsa de tomate para cuerpo, caldo de pollo para riqueza, y comino para calidez. Algunas familias añaden un chorrito de vinagre al final, algunas echan vegetales en cubitos, y otras lo sirven sobre arroz blanco para extra contundencia. Pero los huesos de la receta siempre son los mismos. En Puerto Rico, la sopa de fideo es lo que haces cuando la nevera está vacía pero la despensa aún tiene algo que ofrecer — y nunca decepciona.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="8" data-unit="oz">8 oz</span> de fideos delgados</b> — el tipo vermicelli corto del pasillo latino. Fideos angel hair o espagueti partido funcionan en apuros.',
            '<b><span class="ing-qty" data-base="2" data-unit="tablespoons">2 cucharadas</span> de aceite</b> — vegetal u oliva para sofreír el sofrito.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4 taza</span> de sofrito</b> — casero o comprado. La columna aromática de la sopa.',
            '<b><span class="ing-qty" data-base="1" data-unit="can">1 lata</span> (8 oz) de salsa de tomate</b> — le da al caldo su rojo rico y profundidad de tomate.',
            '<b><span class="ing-qty" data-base="4" data-unit="cups">4 tazas</span> de caldo de pollo</b> — bajo en sodio para controlar la sal. El caldo de vegetales también funciona.',
            '<b><span class="ing-qty" data-base="1" data-unit="teaspoon">1 cucharadita</span> de comino molido</b> — la especia cálida que define el carácter del caldo.',
            '<b>Sal y pimienta al gusto</b>',
            '<b>Cilantro fresco para decorar</b> — un puñado de hojas rotas encima ilumina todo el bol.',
        ],
        "swaps_h3": "Sustituciones en el Mainland",
        "swaps": [
            "<b>¿No hay fideos?</b> Parte espagueti regular o angel hair en pedazos de 1 pulgada y tóstalos igual. El resultado es casi idéntico.",
            "<b>¿No hay sofrito?</b> Pica 3 dientes de ajo + 1/4 taza de cebolla en cubos + 1/4 taza de pimiento verde en cubos. Sofríe hasta ablandar antes de añadir la salsa de tomate.",
            "<b>¿La quieres más contundente?</b> Añade una lata de garbanzos escurridos o papas en cubitos con el caldo para una versión más llenadora.",
        ],
        "steps": [
            "<b>Tuesta los fideos.</b> Coloca los fideos en un sartén seco a fuego medio. Revuelve frecuentemente por 3-4 minutos hasta que estén dorados parejo. No te alejes — pasan de perfectos a quemados rápido. Transfiere a un plato al terminar.",
            "<b>Sofríe el sofrito.</b> Calienta aceite en una olla mediana a fuego medio. Añade el sofrito y cocina 3 minutos, revolviendo ocasionalmente, hasta que esté fragante.",
            "<b>Añade la salsa de tomate.</b> Vierte la salsa de tomate y cocina 2 minutos, revolviendo para integrarla con el sofrito. Esto cocina el sabor crudo de la lata y profundiza el sabor.",
            "<b>Construye el caldo.</b> Vierte el caldo de pollo e incorpora el comino. Lleva todo a un hervor rodante — este es el momento en que la cocina realmente empieza a oler increíble.",
            "<b>Cocina los fideos.</b> Añade los fideos tostados al caldo hirviendo. Baja el fuego a medio-bajo y cocina 8-10 minutos, revolviendo ocasionalmente, hasta que los fideos estén tiernos pero no blandos.",
            "<b>Sazona y sirve.</b> Prueba y ajusta con sal y pimienta. Sirve en tazones y corona con cilantro fresco roto. Sirve caliente — esta sopa no espera.",
        ],
        "tips_h2": "Consejos para una Sopa de Fideo Perfecta",
        "tips": [
            "<b>Tuesta los fideos correctamente.</b> Este es el paso individual más importante. Tostar en sartén seco da a los fideos su sabor a nuez. No lo omitas, y no te apures — 3-4 minutos a fuego medio es el punto ideal.",
            "<b>No sobre-cocines los fideos.</b> Los fideos pasan de tiernos a blandos rápido. Empieza a chequear a los 8 minutos. Deben estar suaves pero con un leve mordisco.",
            "<b>Ajusta el espesor del caldo.</b> A algunas familias les gusta caldosa, a otras espesa. Añade más caldo si la quieres más sopera, o déjala hervir unos minutos extra si la quieres tipo guiso.",
            "<b>Añade el cilantro al final.</b> Cocinar el cilantro mata su sabor fresco y brillante. Rótelo sobre el bol justo antes de servir para el mejor resultado.",
        ],
        "faqs": [
            {"q": "¿Qué fideos debo usar para la sopa de fideo?", "a": "Los fideos son fideos delgados y cortos que se venden en el pasillo latino de la mayoría de supermercados — Goya y otras marcas los tienen. Si no los encuentras, parte espagueti regular o angel hair en pedazos de 1 pulgada. El paso de tostado funciona igual sin importar con qué fideo empieces."},
            {"q": "¿Puedo añadir carne a la sopa de fideo?", "a": "Claro. El pollo desmenuzado es la adición más común — solo incorpora una taza de pollo cocido desmenuzado al añadir el caldo. Algunas familias también añaden jamón en cubitos o carne molida dorada con el sofrito. La receta base es sin carne, pero es fácil hacerla más contundente."},
            {"q": "¿La sopa de fideo debe ser espesa o caldosa?", "a": "Eso es preferencia de familia en familia. Tradicionalmente, la sopa de fideo es caldosa — los fideos absorben algo de líquido al cocinarse, pero debe haber bastante caldo en cada bol. Si te gusta más espesa, déjala hervir más tiempo o usa menos caldo. Algunas familias la sirven sobre arroz blanco para absorber el caldo."},
        ],
    },
    "surullitos": {
        "title": "Surullitos de Maíz — Receta Puertorriqueña de Frituras de Maíz",
        "desc": "Aprende a hacer surullitos de maíz, las queridas frituras dulces de maíz de Puerto Rico — crujientes por fuera, suaves por dentro.",
        "eyebrow": "Frituras",
        "trust": ["25 minutos", "Fácil"],
        "serves": "Rinde 4 porciones:",
        "intro": "Los <b>surullitos</b> son frituras de maíz dulce — una fritura ligeramente dulce, crujiente por fuera y suave por dentro. Son un acompañante querido en barbacoas y reuniones de playa puertorriqueñas. A diferencia de los tostones o bacalaítos savories, los surullitos traen un dulzor suave a la familia de las frituras. Hechos de granos de maíz fresco licuados en una masa suave con harina de maíz, azúcar y un toque de leche, se dejan caer por cucharadas en aceite caliente y se fríen hasta dorar. El exterior consigue un crunch satisfactorio mientras el interior permanece tierno y cremoso con trocitos de textura de maíz. Son el contrapunto perfecto a un plato de pinchos o un bol de asopao, y desaparecen rápido en cualquier reunión donde aparecen.",
        "whatis": [
            "Los surullitos de maíz son frituras de maíz puertorriqueñas hechas de maíz fresco, harina de maíz y una masa simple. El nombre 'surullitos' es un diminutivo — piensa en ellos como pequeños nuggets de maíz. Son miembros de la familia de las frituras, junto a tostones, bacalaítos y empanadillas, pero destacan por su dulzor. Mientras la mayoría de las frituras puertorriqueñas son savories, los surullitos traen un sabor azucarado sutil que los hace únicamente versátiles — combinan igual de bien con un plato principal salado o como snack por sí solos. En kioscos de playa y frituras de carretera por toda la isla, los surullitos siempre están en rotación. Son rápidos de hacer, requieren ingredientes mínimos, y el sabor a maíz fresco brilla en cada bocado.",
        ],
        "ingredients": [
            '<b><span class="ing-qty" data-base="2" data-unit="cups">2 tazas</span> de granos de maíz fresco</b> — cortados de unas 3-4 mazorcas. El maíz en lata también funciona, bien escurrido.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4 taza</span> de harina de maíz</b> — molido fino o medio. Esto da estructura a las frituras.',
            '<b><span class="ing-qty" data-base="2" data-unit="tablespoons">2 cucharadas</span> de azúcar</b> — realza el dulzor natural del maíz.',
            '<b><span class="ing-qty" data-base="0.25" data-unit="cup">1/4 taza</span> de leche</b> — la leche entera añade riqueza. Usa la que tengas a mano.',
            '<b><span class="ing-qty" data-base="1" data-unit="egg">1 huevo</span></b> — une la masa y ayuda al dorado.',
            '<b><span class="ing-qty" data-base="0.5" data-unit="tsp">1/2 cdta</span> de polvo de hornear</b> — da a las frituras una textura ligera e inflada.',
            '<b>Una pizca de sal</b> — balancea el dulzor y resalta el sabor del maíz.',
            '<b>Aceite para freír</b> — unas 1 pulgada en tu sartén. Aceite vegetal o canola.',
        ],
        "swaps_h3": None,
        "swaps": [],
        "steps": [
            "<b>Licúa el maíz.</b> Coloca los granos de maíz en la licuadora o procesador y licúa hasta suavidad. Unos trocitos pequeños están bien — añaden linda textura a las frituras terminadas.",
            "<b>Haz la masa.</b> En un bol, combina el maíz licuado, la harina de maíz, el azúcar, la leche, el huevo, el polvo de hornear y la sal. Revuelve hasta que todo esté bien integrado. La masa debe ser lo bastante espesa para mantener su forma al caer de una cuchara.",
            "<b>Calienta el aceite.</b> Vierte unas 1 pulgada de aceite en un sartén pesado y calienta a fuego medio a 350°F. Prueba con una gotita de masa — debe chisporrotear de inmediato y flotar.",
            "<b>Fríe los surullitos.</b> Deja caer cucharadas de masa del tamaño de una cucharada en el aceite caliente. No satures — fríe 4-5 a la vez. Cocina 2-3 minutos por lado hasta dorado profundo.",
            "<b>Escurre y sirve.</b> Transfiere los surullitos fritos a un plato forrado con toallas de papel. Sirve tibios — están mejores recién hechos, aunque las sobras se recalientan bien en el horno.",
        ],
        "tips_h2": "Consejos para Surullitos Perfectos",
        "tips": [
            "<b>Usa maíz fresco cuando puedas.</b> Las mazorcas frescas dan el mejor dulzor y textura. Pero el maíz en lata o congelado funciona en apuros — solo escúrrelo y sécalo antes de licuar.",
            "<b>No los hagas muy grandes.</b> Los surullitos deben ser del tamaño de un bocado — como una cucharada de masa cada uno. Las frituras grandes no se cocinan por dentro y quedan pastosas en el centro.",
            "<b>Mantén el aceite a 350°F.</b> Si el aceite está muy caliente, el exterior se quema antes de que el interior cocine. Si está muy frío, las frituras absorben demasiado aceite y quedan grasosas.",
            "<b>Sirve de inmediato.</b> Los surullitos están en su mejor momento directo de la freidora. Si necesitas retenerlos, mantenlos calientes en horno a 200°F sobre rejilla hasta 30 minutos.",
        ],
        "faqs": [
            {"q": "¿Debo usar maíz fresco o en lata?", "a": "El maíz fresco da el mejor sabor y textura — el dulzor natural es más brillante y los granos tienen más mordisco. Pero el maíz en lata (bien escurrido) o congelado (descongelado) funciona perfectamente. La receta fue diseñada para ser flexible. Si usas en lata, seca los granos antes de licuar para evitar una masa aguada."},
            {"q": "¿Puedo añadir queso a la masa?", "a": "¡Sí! Añadir 1/4 taza de queso fresco rallado o mozzarella a la masa es una variación popular. El queso se derrite por dentro y añade un contraste salado al maíz dulce. Algunas personas también añaden una cucharada de cilantro picado o una pizca de jalapeño para sabor extra."},
            {"q": "¿Los surullitos son dulces o salados?", "a": "Están en algún punto intermedio — ligeramente dulces con una base salada. El azúcar de la receta realza el dulzor natural del maíz, pero la sal y el huevo evitan que sepan a postre. Están pensados como acompañante o snack, no como golosina. Piensa en ellos como una fritura de cornbread salada-dulce."},
        ],
    },
}