// AUTO-GENERATED by scripts (do not edit) — recipe blog unlock CTAs.
export const RECIPE_UNLOCKS = {
  "alcapurrias": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "arepas-de-coco": {
    "sku": "postres-boricuas",
    "link": "https://sofritostudio.gumroad.com/l/postres-boricuas",
    "price": 12,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "arroz-con-dulce": {
    "sku": "postres-boricuas",
    "link": "https://sofritostudio.gumroad.com/l/postres-boricuas",
    "price": 12,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "arroz-con-gandules": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "arroz-con-pollo": {
    "sku": "starter-kit",
    "link": "https://sofritostudio.gumroad.com/l/sofrito-starter-kit",
    "price": 9,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "asopao": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "avena": {
    "sku": "boricua-breakfasts",
    "link": "https://sofritostudio.gumroad.com/l/boricua-breakfasts",
    "price": 12,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "bacalaitos": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "besitos-de-coco": {
    "sku": "postres-boricuas",
    "link": "https://sofritostudio.gumroad.com/l/postres-boricuas",
    "price": 12,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "cafe-con-leche": {
    "sku": "boricua-breakfasts",
    "link": "https://sofritostudio.gumroad.com/l/boricua-breakfasts",
    "price": 12,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "chocolate-caliente": {
    "sku": "boricua-breakfasts",
    "link": "https://sofritostudio.gumroad.com/l/boricua-breakfasts",
    "price": 12,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "chuletas": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "coquito": {
    "sku": "coquito-guide",
    "link": "https://sofritostudio.gumroad.com/l/coquito-guide",
    "price": 12,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "empanadillas": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "flan": {
    "sku": "starter-kit",
    "link": "https://sofritostudio.gumroad.com/l/sofrito-starter-kit",
    "price": 9,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "habichuelas": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "sofrito": {
    "sku": "starter-kit",
    "link": "https://sofritostudio.gumroad.com/l/sofrito-starter-kit",
    "price": 9,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "tostones": {
    "sku": "starter-kit",
    "link": "https://sofritostudio.gumroad.com/l/sofrito-starter-kit",
    "price": 9,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "majarete": {
    "sku": "postres-boricuas",
    "link": "https://sofritostudio.gumroad.com/l/postres-boricuas",
    "price": 12,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "mallorcas": {
    "sku": "boricua-breakfasts",
    "link": "https://sofritostudio.gumroad.com/l/boricua-breakfasts",
    "price": 12,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "mofongo": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "papa-rellena": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "pastelillos": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "pernil": {
    "sku": "starter-kit",
    "link": "https://sofritostudio.gumroad.com/l/sofrito-starter-kit",
    "price": 9,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "pinchos": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "quesitos": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "sancocho": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "sopa-de-fideo": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "surullitos": {
    "sku": "mesa",
    "link": "https://sofritostudio.gumroad.com/l/cmfkg",
    "price": 47,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  },
  "tembleque": {
    "sku": "postres-boricuas",
    "link": "https://sofritostudio.gumroad.com/l/postres-boricuas",
    "price": 12,
    "label": {
      "en": "Get the full guide",
      "es": "Consigue la guía completa"
    }
  }
};
