// AUTO-GENERATED by scripts (do not edit) — edge Recipe/Product JSON-LD.
export const RECIPE_SCHEMA = {
  "alcapurrias": {
    "name": "Alcapurrias — Authentic Puerto Rican Stuffed Fritters Recipe",
    "description": "The ultimate Puerto Rican street food — shredded green banana and yautía fritters stuffed with seasoned ground beef.",
    "image": "../images/rec-alcapurrias.webp",
    "prep_min": 30,
    "cook_min": 20,
    "ingredients": [
      "Plantain",
      "Pork",
      "Garlic"
    ],
    "category": "Snack",
    "cuisine": "Afro-Caribbean",
    "url": "blog/alcapurrias.html"
  },
  "arepas-de-coco": {
    "name": "Arepas de Coco — Authentic Puerto Rican Coconut Flour Fritters Recipe",
    "description": "Coconut flour fritters — crispy, fluffy, and naturally gluten-free. A beach-favorite fritura from Puerto Rico.",
    "image": "../images/rec-arepas-coco.webp",
    "prep_min": 15,
    "cook_min": 25,
    "ingredients": [
      "Coconut",
      "Cornmeal",
      "Sugar"
    ],
    "category": "Dessert",
    "cuisine": "Taino heritage",
    "url": "blog/arepas-de-coco.html"
  },
  "arroz-con-dulce": {
    "name": "Arroz con Dulce — Puerto Rican Sweet Coconut Rice Pudding Recipe",
    "description": "Puerto Rico's sweet coconut rice pudding — the holiday dessert that's actually easy to make.",
    "image": "../images/rec-arroz-con-dulce.webp",
    "prep_min": 15,
    "cook_min": 50,
    "ingredients": [
      "Rice",
      "Coconut",
      "Milk",
      "Ginger",
      "Sugar"
    ],
    "category": "Dessert",
    "cuisine": "Puerto Rican",
    "url": "blog/arroz-con-dulce.html"
  },
  "arroz-con-gandules": {
    "name": "Arroz con Gandules — Authentic Puerto Rican Rice and Pigeon Peas Recipe",
    "description": "Puerto Rico's national dish — rice, pigeon peas, and sofrito. The one-pot meal every boricua makes for holidays.",
    "image": "../images/rec-arroz-gandules.webp",
    "prep_min": 20,
    "cook_min": 60,
    "ingredients": [
      "Rice",
      "Beans",
      "Pork",
      "Sofrito"
    ],
    "category": "Side",
    "cuisine": "Puerto Rican",
    "url": "blog/arroz-con-gandules.html"
  },
  "arroz-con-pollo": {
    "name": "Arroz con Pollo — Authentic Puerto Rican Chicken and Rice Recipe",
    "description": "One pot, chicken and rice, deeply flavored with sofrito and sazon. Puerto Rican comfort food at its best.",
    "image": "../images/rec-arroz.webp",
    "prep_min": 15,
    "cook_min": 50,
    "ingredients": [
      "Rice",
      "Chicken",
      "Sofrito",
      "Peas"
    ],
    "category": "Dinner",
    "cuisine": "Puerto Rican",
    "url": "blog/arroz-con-pollo.html"
  },
  "asopao": {
    "name": "Asopao de Pollo — Authentic Puerto Rican Chicken and Rice Stew Recipe",
    "description": "Thicker than soup, wetter than arroz con pollo — Puerto Rican soul food at its finest.",
    "image": "../images/rec-asopao.webp",
    "prep_min": 15,
    "cook_min": 45,
    "ingredients": [
      "Rice",
      "Chicken",
      "Sofrito"
    ],
    "category": "Dinner",
    "cuisine": "Puerto Rican",
    "url": "blog/asopao.html"
  },
  "avena": {
    "name": "Avena — Authentic Puerto Rican Oatmeal Drink Recipe",
    "description": "Creamy, cinnamon-spiced Puerto Rican oatmeal drink — the breakfast smoothie before smoothies existed.",
    "image": "../images/rec-avena.webp",
    "prep_min": 5,
    "cook_min": 10,
    "ingredients": [
      "Oats",
      "Milk",
      "Cinnamon"
    ],
    "category": "Breakfast",
    "cuisine": "Puerto Rican",
    "url": "blog/avena.html"
  },
  "bacalaitos": {
    "name": "Bacalaítos — Authentic Puerto Rican Codfish Fritters Recipe",
    "description": "Salty, crispy codfish fritters that every Puerto Rican grew up eating at the beach, at parties, and from street vendors.",
    "image": "../images/rec-bacalaitos.webp",
    "prep_min": 25,
    "cook_min": 20,
    "ingredients": [
      "Cod",
      "Flour",
      "Garlic"
    ],
    "category": "Snack",
    "cuisine": "Afro-Caribbean",
    "url": "blog/bacalaitos.html"
  },
  "besitos-de-coco": {
    "name": "Besitos de Coco — Authentic Puerto Rican Coconut Macaroons Recipe",
    "description": "Coconut macaroons shaped into little kisses — chewy, sweet, and impossibly simple.",
    "image": "../images/rec-besitos-coco.webp",
    "prep_min": 15,
    "cook_min": 20,
    "ingredients": [
      "Coconut",
      "Egg",
      "Sugar"
    ],
    "category": "Dessert",
    "cuisine": "Puerto Rican",
    "url": "blog/besitos-de-coco.html"
  },
  "cafe-con-leche": {
    "name": "Café con Leche — Authentic Puerto Rican Coffee with Milk Recipe",
    "description": "Strong, sweet, and creamy — the ritual that starts every morning on the island.",
    "image": "../images/rec-cafe-con-leche.webp",
    "prep_min": 5,
    "cook_min": 5,
    "ingredients": [
      "Coffee",
      "Milk"
    ],
    "category": "Breakfast",
    "cuisine": "Puerto Rican",
    "url": "blog/cafe-con-leche.html"
  },
  "chocolate-caliente": {
    "name": "Chocolate Caliente Boricua — Authentic Puerto Rican Hot Chocolate Recipe",
    "description": "Real Puerto Rican hot chocolate — thick, cinnamon-spiced, and made with actual chocolate. Not the packet stuff.",
    "image": "../images/rec-chocolate.webp",
    "prep_min": 5,
    "cook_min": 10,
    "ingredients": [
      "Chocolate",
      "Milk",
      "Cinnamon"
    ],
    "category": "Breakfast",
    "cuisine": "Puerto Rican",
    "url": "blog/chocolate-caliente.html"
  },
  "chuletas": {
    "name": "Chuletas Kan Kan — Puerto Rican Pork Chops Recipe",
    "description": "Puerto Rico's iconic crispy, juicy double-cut pork chops — breaded and fried to golden perfection.",
    "image": "../images/rec-chuletas.webp",
    "prep_min": 15,
    "cook_min": 20,
    "ingredients": [
      "Pork",
      "Garlic",
      "Sofrito"
    ],
    "category": "Dinner",
    "cuisine": "Puerto Rican",
    "url": "blog/chuletas.html"
  },
  "coquito": {
    "name": "Coquito — Authentic Puerto Rican Coconut Holiday Drink Recipe",
    "description": "Puerto Rico's coconut eggnog — the holiday drink that replaces everything from November through January. Every family has a secret recipe.",
    "image": "../images/rec-coquito.webp",
    "prep_min": 10,
    "cook_min": 5,
    "ingredients": [
      "Coconut",
      "Rum",
      "Milk",
      "Cinnamon"
    ],
    "category": "Drink",
    "cuisine": "Puerto Rican",
    "url": "blog/coquito.html"
  },
  "empanadillas": {
    "name": "Empanadillas — Authentic Puerto Rican Beef Empanada Recipe",
    "description": "Puerto Rico's answer to the empanada — larger, softer dough pockets stuffed with seasoned beef.",
    "image": "../images/rec-empanadillas.webp",
    "prep_min": 40,
    "cook_min": 20,
    "ingredients": [
      "Flour",
      "Beef",
      "Sofrito"
    ],
    "category": "Lunch",
    "cuisine": "Puerto Rican",
    "url": "blog/empanadillas.html"
  },
  "flan": {
    "name": "Flan de Queso — The Creamiest Puerto Rican Flan Recipe",
    "description": "Rich, silky cheesecake flan with perfect caramel — the Puerto Rican dessert everyone asks for.",
    "image": "../images/rec-flan.webp",
    "prep_min": 20,
    "cook_min": 60,
    "ingredients": [
      "Egg",
      "Milk",
      "Sugar"
    ],
    "category": "Dessert",
    "cuisine": "Puerto Rican",
    "url": "blog/flan.html"
  },
  "habichuelas": {
    "name": "Habichuelas Guisadas — Authentic Puerto Rican Stewed Beans Recipe",
    "description": "The everyday Puerto Rican side dish — thick, savory bean stew with calabaza that accompanies rice on virtually every plate.",
    "image": "../images/rec-habichuelas.webp",
    "prep_min": 10,
    "cook_min": 35,
    "ingredients": [
      "Beans",
      "Sofrito",
      "Pork"
    ],
    "category": "Side",
    "cuisine": "Puerto Rican",
    "url": "blog/habichuelas.html"
  },
  "sofrito": {
    "name": "Homemade Sofrito — Puerto Rican Flavor Base Recipe",
    "description": "The flavor base of every Puerto Rican dish — recao, garlic, peppers, and herbs. Make a batch in 20 minutes.",
    "image": "../images/rec-sofrito.webp",
    "prep_min": 20,
    "cook_min": 0,
    "ingredients": [
      "Pepper",
      "Garlic",
      "Herbs",
      "Onion"
    ],
    "category": "Side",
    "cuisine": "Puerto Rican",
    "url": "blog/sofrito.html"
  },
  "tostones": {
    "name": "How to Make Perfect Tostones (Twice-Fried Plantains)",
    "description": "Crispy golden twice-fried green plantains the Puerto Rican way — step-by-step with tips for the crunchiest results.",
    "image": "../images/rec-tostones.webp",
    "prep_min": 15,
    "cook_min": 15,
    "ingredients": [
      "Plantain",
      "Garlic"
    ],
    "category": "Side",
    "cuisine": "Puerto Rican",
    "url": "blog/tostones.html"
  },
  "majarete": {
    "name": "Majarete — Authentic Puerto Rican Corn and Coconut Pudding Recipe",
    "description": "Warm corn and coconut pudding — the humble, comforting dessert every Puerto Rican grandmother made.",
    "image": "../images/rec-majarete.webp",
    "prep_min": 10,
    "cook_min": 30,
    "ingredients": [
      "Cornmeal",
      "Coconut",
      "Sugar"
    ],
    "category": "Dessert",
    "cuisine": "Taino heritage",
    "url": "blog/majarete.html"
  },
  "mallorcas": {
    "name": "Mallorcas — Puerto Rican Sweet Bread Rolls Recipe",
    "description": "Buttery, slightly dense sweet bread rolls — the Puerto Rican breakfast staple dusted with powdered sugar and dipped in café con leche.",
    "image": "../images/rec-mallorcas.webp",
    "prep_min": 30,
    "cook_min": 20,
    "ingredients": [
      "Flour",
      "Egg",
      "Butter",
      "Sugar"
    ],
    "category": "Breakfast",
    "cuisine": "Puerto Rican",
    "url": "blog/mallorcas.html"
  },
  "mofongo": {
    "name": "Mofongo — Authentic Puerto Rican Mashed Plantains Recipe",
    "description": "Fried green plantains mashed with garlic, chicharron, and olive oil. Puerto Rico's most iconic dish.",
    "image": "../images/rec-mofongo.webp",
    "prep_min": 20,
    "cook_min": 25,
    "ingredients": [
      "Plantain",
      "Garlic",
      "Pork"
    ],
    "category": "Dinner",
    "cuisine": "Afro-Caribbean",
    "url": "blog/mofongo.html"
  },
  "papa-rellena": {
    "name": "Papa Rellena — Authentic Puerto Rican Stuffed Potato Balls Recipe",
    "description": "Stuffed potato balls — crispy, golden, and worth every calorie. The fried comfort food every boricua fights over.",
    "image": "../images/rec-papa-rellena.webp",
    "prep_min": 40,
    "cook_min": 20,
    "ingredients": [
      "Potato",
      "Beef",
      "Egg"
    ],
    "category": "Lunch",
    "cuisine": "Puerto Rican",
    "url": "blog/papa-rellena.html"
  },
  "pastelillos": {
    "name": "Pastelillos de Carne — Puerto Rican Beef Pastry Pockets Recipe",
    "description": "Flaky golden pastry pockets — Puerto Rico's most beloved snack with savory beef, sweet raisins, and briny alcaparrado.",
    "image": "../images/rec-pastelillos.webp",
    "prep_min": 40,
    "cook_min": 20,
    "ingredients": [
      "Flour",
      "Beef",
      "Sofrito"
    ],
    "category": "Lunch",
    "cuisine": "Puerto Rican",
    "url": "blog/pastelillos.html"
  },
  "pernil": {
    "name": "Pernil Asado — Slow-Roasted Puerto Rican Pork Shoulder Recipe",
    "description": "Slow-roasted pork shoulder with crispy skin and garlicky mojo criollo. The Nochebuena centerpiece.",
    "image": "../images/pernil-course.jpg",
    "prep_min": 20,
    "cook_min": 300,
    "ingredients": [
      "Pork",
      "Garlic",
      "Herbs"
    ],
    "category": "Dinner",
    "cuisine": "Puerto Rican",
    "url": "blog/pernil.html"
  },
  "pinchos": {
    "name": "Pinchos — Puerto Rican Grilled Skewers Recipe",
    "description": "The beach food, the party food, the 'I don't feel like cooking' food. Every kiosk has their own marinade.",
    "image": "../images/rec-pinchos.webp",
    "prep_min": 20,
    "cook_min": 15,
    "ingredients": [
      "Pork",
      "Garlic",
      "Sauce"
    ],
    "category": "Dinner",
    "cuisine": "Puerto Rican",
    "url": "blog/pinchos.html"
  },
  "quesitos": {
    "name": "Quesitos — Authentic Puerto Rican Cream Cheese Pastries Recipe",
    "description": "Cream cheese-filled puff pastries — the golden, sugar-dusted bakery staple of Puerto Rico.",
    "image": "../images/rec-quesitos.webp",
    "prep_min": 15,
    "cook_min": 20,
    "ingredients": [
      "Puff pastry",
      "Cream cheese",
      "Sugar"
    ],
    "category": "Dessert",
    "cuisine": "Puerto Rican",
    "url": "blog/quesitos.html"
  },
  "sancocho": {
    "name": "Sancocho — Authentic Puerto Rican Seven-Meat Hearty Stew Recipe",
    "description": "Puerto Rico's ultimate comfort stew — mixed meats and root vegetables simmered into pure magic.",
    "image": "../images/rec-sancocho.webp",
    "prep_min": 30,
    "cook_min": 120,
    "ingredients": [
      "Beef",
      "Pork",
      "Chicken",
      "Plantain",
      "Yuca",
      "Corn"
    ],
    "category": "Dinner",
    "cuisine": "Puerto Rican",
    "url": "blog/sancocho.html"
  },
  "sopa-de-fideo": {
    "name": "Sopa de Fideo — Authentic Puerto Rican Toasted Noodle Soup Recipe",
    "description": "Toasted noodles simmered in tomato broth with sofrito — Puerto Rican comfort food in a bowl.",
    "image": "../images/rec-sopa-fideo.webp",
    "prep_min": 10,
    "cook_min": 20,
    "ingredients": [
      "Pasta",
      "Chicken",
      "Sofrito"
    ],
    "category": "Lunch",
    "cuisine": "Puerto Rican",
    "url": "blog/sopa-de-fideo.html"
  },
  "surullitos": {
    "name": "Surullitos de Maíz — Puerto Rican Sweet Corn Fritters Recipe",
    "description": "Sweet corn fritters that are crispy outside, soft inside — a beloved fritura at barbecues and beach gatherings.",
    "image": "../images/rec-surullitos.webp",
    "prep_min": 15,
    "cook_min": 15,
    "ingredients": [
      "Cornmeal",
      "Cheese",
      "Sugar"
    ],
    "category": "Snack",
    "cuisine": "Puerto Rican",
    "url": "blog/surullitos.html"
  },
  "tembleque": {
    "name": "Tembleque — Puerto Rican Coconut Milk Pudding Recipe",
    "description": "A coconut milk pudding that literally jiggles — the holiday dessert on every Puerto Rican Christmas table.",
    "image": "../images/rec-tembleque.webp",
    "prep_min": 10,
    "cook_min": 25,
    "ingredients": [
      "Coconut",
      "Milk",
      "Cornstarch",
      "Cinnamon"
    ],
    "category": "Dessert",
    "cuisine": "Taino heritage",
    "url": "blog/tembleque.html"
  }
};
